apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akb-secret-store-tls
  labels:
    app.kubernetes.io/part-of: akb
    app.kubernetes.io/component: secret-manager
spec:
  secretName: akb-secret-store-tls # pragma: allowlist secret
  issuerRef:
    kind: __CERT_ISSUER_KIND__
    name: __CERT_ISSUER_NAME__
  dnsNames:
    - __SERVICE__
    - __SERVICE__.__NAMESPACE__
    - __SERVICE__.__NAMESPACE__.svc
    - __SERVICE__.__NAMESPACE__.svc.__CLUSTER_DOMAIN__
    - __STATEFULSET__-0.__STATEFULSET__-internal
    - __STATEFULSET__-0.__STATEFULSET__-internal.__NAMESPACE__
    - __STATEFULSET__-0.__STATEFULSET__-internal.__NAMESPACE__.svc
    - __STATEFULSET__-0.__STATEFULSET__-internal.__NAMESPACE__.svc.__CLUSTER_DOMAIN__
    - __STATEFULSET__-1.__STATEFULSET__-internal
    - __STATEFULSET__-1.__STATEFULSET__-internal.__NAMESPACE__
    - __STATEFULSET__-1.__STATEFULSET__-internal.__NAMESPACE__.svc
    - __STATEFULSET__-1.__STATEFULSET__-internal.__NAMESPACE__.svc.__CLUSTER_DOMAIN__
    - __STATEFULSET__-2.__STATEFULSET__-internal
    - __STATEFULSET__-2.__STATEFULSET__-internal.__NAMESPACE__
    - __STATEFULSET__-2.__STATEFULSET__-internal.__NAMESPACE__.svc
    - __STATEFULSET__-2.__STATEFULSET__-internal.__NAMESPACE__.svc.__CLUSTER_DOMAIN__
