{{- if and (eq .Values.secretManager.mode "bundled") .Values.secretManager.tls.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akb-secret-store-tls
  labels:
    {{- include "akb.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-manager
spec:
  secretName: {{ .Values.secretManager.tls.secretName }}
  issuerRef:
    kind: {{ .Values.secretManager.tls.certificate.issuerKind }}
    name: {{ .Values.secretManager.tls.certificate.issuerName }}
  dnsNames:
    - akb-secret-store
    - akb-secret-store.{{ .Release.Namespace }}
    - akb-secret-store.{{ .Release.Namespace }}.svc
    - akb-secret-store.{{ .Release.Namespace }}.svc.{{ .Values.secretManager.tls.certificate.clusterDomain }}
    {{- range $index := until 3 }}
    - akb-secret-store-{{ $index }}.akb-secret-store-internal
    - akb-secret-store-{{ $index }}.akb-secret-store-internal.{{ $.Release.Namespace }}
    - akb-secret-store-{{ $index }}.akb-secret-store-internal.{{ $.Release.Namespace }}.svc
    - akb-secret-store-{{ $index }}.akb-secret-store-internal.{{ $.Release.Namespace }}.svc.{{ $.Values.secretManager.tls.certificate.clusterDomain }}
    {{- end }}
{{- end }}
