#!/usr/bin/env node
// Generate the Keycloak login theme's token layer from the app's design tokens.
//
// The app's one token source is `frontend/src/index.css`: a Tailwind v4
// `@theme` block (light) and a `.dark` override. This copies every custom
// property from those blocks, renamed `--color-x` -> `--akb-color-x`, into
// `akb-tokens.generated.css`. Nothing else in the theme may hold a colour
// literal; the vocabulary layer maps these onto the names the templates use.
//
//   node keycloak-theme/scripts/theme-tokens.mjs           # write
//   node keycloak-theme/scripts/theme-tokens.mjs --check   # fail on drift
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const frontend = resolve(here, "../..");
export const SOURCE = resolve(frontend, "src/index.css");
export const OUTPUT = resolve(frontend, "keycloak-theme/akb/login/resources/css/akb-tokens.generated.css");

function stripComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\//g, "");
}

// The body of each top-level block whose header matches, in source order.
function topLevelBlocks(css, headerPattern) {
  const blocks = [];
  let depth = 0;
  let start = -1;
  let header = "";
  let headerStart = 0;
  for (let i = 0; i < css.length; i += 1) {
    const ch = css[i];
    if (ch === "{") {
      if (depth === 0) {
        header = css.slice(headerStart, i).trim();
        start = i + 1;
      }
      depth += 1;
    } else if (ch === "}") {
      depth -= 1;
      if (depth < 0) throw new Error("unbalanced braces in index.css");
      if (depth === 0) {
        if (headerPattern.test(header)) blocks.push(css.slice(start, i));
        headerStart = i + 1;
      }
    } else if (ch === ";" && depth === 0) {
      headerStart = i + 1;
    }
  }
  if (depth !== 0) throw new Error("unbalanced braces in index.css");
  return blocks;
}

// `name: value` declarations at the top of a block body (no nested rules).
function declarations(body) {
  const out = [];
  let depth = 0;
  let current = "";
  for (const ch of body) {
    if (ch === "(") depth += 1;
    if (ch === ")") depth -= 1;
    if (ch === "{" || ch === "}") throw new Error("nested rule inside a token block");
    if (ch === ";" && depth === 0) {
      if (current.trim()) out.push(current.trim());
      current = "";
    } else {
      current += ch;
    }
  }
  if (current.trim()) out.push(current.trim());
  return out.map((decl) => {
    const colon = decl.indexOf(":");
    if (colon < 0) throw new Error(`not a declaration: ${decl}`);
    return [decl.slice(0, colon).trim(), decl.slice(colon + 1).trim().replace(/\s+/g, " ")];
  });
}

function rename(name) {
  return name.startsWith("--") ? `--akb-${name.slice(2)}` : name;
}

function renameReferences(value) {
  return value.replace(/var\(\s*--([A-Za-z0-9_-]+)/g, "var(--akb-$1");
}

export function buildTokens(source = readFileSync(SOURCE, "utf8")) {
  const css = stripComments(source);
  const light = [
    ...topLevelBlocks(css, /^@theme(\s+static)?$/).flatMap(declarations),
  ].filter(([name]) => name.startsWith("--"));
  const dark = topLevelBlocks(css, /^\.dark$/).flatMap(declarations);
  if (light.length === 0 || dark.length === 0) {
    throw new Error("index.css no longer has an @theme block and a .dark block");
  }
  const render = (decls, indent) =>
    decls.map(([name, value]) => `${indent}${rename(name)}: ${renameReferences(value)};`).join("\n");
  return [
    "/* GENERATED by keycloak-theme/scripts/theme-tokens.mjs from src/index.css.",
    " * Do not edit: change src/index.css and run `pnpm run theme:tokens`. */",
    ":root {",
    render(light, "  "),
    "}",
    "",
    ':root[data-theme="dark"] {',
    render(dark, "  "),
    "}",
    "",
    "/* No script ran, so no explicit choice exists: follow the system. */",
    "@media (prefers-color-scheme: dark) {",
    "  :root:not([data-theme]) {",
    render(dark, "    "),
    "  }",
    "}",
    "",
  ].join("\n");
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const generated = buildTokens();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUTPUT, "utf8");
    } catch {
      // reported below
    }
    if (current !== generated) {
      console.error("akb-tokens.generated.css is out of date with src/index.css; run `pnpm run theme:tokens`.");
      process.exit(1);
    }
    console.log("keycloak theme tokens match src/index.css");
  } else {
    writeFileSync(OUTPUT, generated);
    console.log(`wrote ${OUTPUT}`);
  }
}
