/* Generated by akb gen types. Do not edit manually. */
/* Source vault: eng */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type AkbRef<T, Target extends string> = T & { readonly __akbRef?: Target };

export interface Database {
  public: {
    Tables: {
      "tasks": {
        Row: {
          "title": string;
          "status": "todo" | "done";
          "owner_id": AkbRef<string, "users.id"> | null;
          "metadata": Json | null;
        };
        Insert: {
          "title": string;
          "status"?: "todo" | "done";
          "owner_id"?: AkbRef<string, "users.id"> | null;
          "metadata"?: Json | null;
        };
        Update: {
          "title"?: string;
          "status"?: "todo" | "done";
          "owner_id"?: AkbRef<string, "users.id"> | null;
          "metadata"?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
            onDelete: "set null";
          },
        ];
      };
    };
  };
}

export type AkbSchema = Database;
