profile: standalone-sso
sso:
  enabled: true
  localRealmLogin:
    enabled: true
    displayName: AKB account
secretManager:
  mode: manual
  engine: ""
secretSync:
  enabled: false
openbao:
  enabled: false
hashicorpVault:
  enabled: false
