global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  dev:
    enabled: true
  standalone:
    enabled: false
  ha:
    enabled: false
  dataStorage:
    enabled: false
  auditStorage:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    create: true
  authDelegator:
    enabled: true

ui:
  enabled: false

csi:
  enabled: false
