import { matchPath } from "react-router-dom";
import type { NodeKind, TreeNode } from "@/hooks/use-vault-tree";

/**
 * Resolve which tree node (if any) the current URL refers to. Returns a
 * stable `kind:path` signature so call sites can compare without keeping
 * node identity across renders.
 *
 * Document URLs are always in canonical `path` form — the legacy
 * `d-XXXXXXXX` short-hash id is no longer generated by the backend and
 * the tree never carries that id either.
 */
export function activePathFromRoute(pathname: string, tree: TreeNode[] | null): string | null {
  if (!tree) return null;

  const doc = matchPath("/vault/:name/doc/:id", pathname);
  if (doc) {
    const ref = decodeURIComponent(doc.params.id ?? "");
    const hit = findDoc(tree, ref);
    return hit ? signatureOf(hit) : null;
  }

  const table = matchPath("/vault/:name/table/:table", pathname);
  if (table) return `table:${decodeURIComponent(table.params.table ?? "")}`;

  const file = matchPath("/vault/:name/file/:id", pathname);
  if (file) return `file:${decodeURIComponent(file.params.id ?? "")}`;

  return null;
}

export function signatureOf(n: TreeNode): string {
  return `${n.kind}:${n.path}`;
}

/**
 * Walk the tree looking for a document whose `path` or canonical `uri`
 * matches the given ref. We deliberately *don't* fall back on partial-path
 * matching anymore — DocumentPage canonicalizes URLs, so a clean path is
 * the only input this function needs to handle. The legacy `raw.id` /
 * `raw.doc_id` fields no longer exist after the URI cutover.
 */
export function findDoc(nodes: TreeNode[], ref: string): TreeNode | null {
  for (const n of nodes) {
    if (n.kind === "document") {
      const raw = n.raw || {};
      if (n.path === ref || raw.uri === ref) return n;
    } else if (n.children) {
      const hit = findDoc(n.children, ref);
      if (hit) return hit;
    }
  }
  return null;
}

export function countDocs(n: TreeNode): number {
  if (n.kind === "document") return 1;
  if (!n.children) return 0;
  return n.children.reduce((s, c) => s + countDocs(c), 0);
}

export function leafHref(vault: string, node: TreeNode): string {
  switch (node.kind) {
    case "document": return `/vault/${vault}/doc/${encodeURIComponent(node.path)}`;
    case "table":    return `/vault/${vault}/table/${encodeURIComponent(node.path)}`;
    case "file":     return `/vault/${vault}/file/${encodeURIComponent(node.path)}`;
    default:         return `/vault/${vault}`;
  }
}

/**
 * Return a subset of the tree whose names/paths contain `q` (lowercased).
 * Collections are retained if any descendant matches.
 */
export function filterTree(nodes: TreeNode[], q: string): TreeNode[] {
  const out: TreeNode[] = [];
  for (const n of nodes) {
    if (n.kind === "collection") {
      const kept = n.children ? filterTree(n.children, q) : [];
      if (kept.length > 0 || n.name.toLowerCase().includes(q)) {
        out.push({ ...n, children: kept });
      }
    } else if (n.name.toLowerCase().includes(q) || n.path.toLowerCase().includes(q)) {
      out.push(n);
    }
  }
  return out;
}

export type ResourceKind = Exclude<NodeKind, "collection">;

export interface FlatNodeRow {
  type: "node";
  node: TreeNode;
  depth: number;
  sig: string;
  /** True iff this collection is currently expanded. `false` for leaves. */
  isOpen: boolean;
}

export interface FlatKindGroupRow {
  type: "kind-group";
  kind: ResourceKind;
  parentPath: string;
  depth: number;
  sig: string;
  count: number;
  isOpen: boolean;
}

export interface FlatMoreRow {
  type: "more";
  kind: ResourceKind;
  parentPath: string;
  depth: number;
  sig: string;
  visibleCount: number;
  totalCount: number;
}

export type FlatRow = FlatNodeRow | FlatKindGroupRow | FlatMoreRow;

export const RESOURCE_PREVIEW_SIZE = 20;

const RESOURCE_KIND_ORDER: ResourceKind[] = ["document", "table", "file"];

export function kindGroupKey(parentPath: string, kind: ResourceKind): string {
  return `${parentPath || "$root"}:${kind}`;
}

export function filterTreeByKind(
  nodes: TreeNode[],
  kind: ResourceKind | "all",
): TreeNode[] {
  if (kind === "all") return nodes;
  const out: TreeNode[] = [];
  for (const node of nodes) {
    if (node.kind === "collection") {
      const children = filterTreeByKind(node.children ?? [], kind);
      if (children.length > 0) out.push({ ...node, children });
    } else if (node.kind === kind) {
      out.push(node);
    }
  }
  return out;
}

interface FlattenVisibleOptions {
  /** Groups are open by default. Keys in this set are explicitly collapsed. */
  collapsedKindGroups?: ReadonlySet<string>;
  /** Per-group visible leaf limits; absent groups use RESOURCE_PREVIEW_SIZE. */
  kindLimits?: ReadonlyMap<string, number>;
  /** Keep the current route visible even when it falls beyond a preview. */
  activeSig?: string | null;
}

/**
 * Flatten the tree into the exact DFS order the explorer renders, annotating
 * each row with depth / signature / open state. `forceOpen` reflects the
 * "filter active — expand all matches" mode.
 *
 * Flat rendering with primitive props is what makes React.memo on the row
 * component effective — a recursive render with a Set prop would fail
 * shallow-equal on every toggle.
 */
export function flattenVisible(
  nodes: TreeNode[],
  expanded: Set<string>,
  forceOpen: boolean,
  options: FlattenVisibleOptions = {},
): FlatRow[] {
  const out: FlatRow[] = [];
  const collapsed = options.collapsedKindGroups ?? new Set<string>();
  const limits = options.kindLimits ?? new Map<string, number>();

  const pushNode = (node: TreeNode, depth: number, isOpen = false) => {
    out.push({
      type: "node",
      node,
      depth,
      sig: signatureOf(node),
      isOpen,
    });
  };

  const visit = (list: TreeNode[], depth: number, parentPath: string) => {
    // Collections keep their natural hierarchy. Resource kinds become peer
    // disclosure rows only when the sibling set mixes kinds or is too large to
    // scan safely. A small single-kind collection stays compact.
    const collections = list.filter((node) => node.kind === "collection");
    const leaves = list.filter((node) => node.kind !== "collection");

    for (const n of collections) {
      const isOpen = n.kind === "collection" && (forceOpen || expanded.has(n.path));
      pushNode(n, depth, isOpen);
      if (isOpen && n.children) visit(n.children, depth + 1, n.path);
    }

    const presentKinds = RESOURCE_KIND_ORDER.filter((kind) =>
      leaves.some((leaf) => leaf.kind === kind),
    );
    const shouldGroup =
      presentKinds.length > 1 || leaves.length > RESOURCE_PREVIEW_SIZE;

    if (!shouldGroup) {
      for (const leaf of leaves) pushNode(leaf, depth);
      return;
    }

    for (const kind of presentKinds) {
      const kindLeaves = leaves.filter((leaf) => leaf.kind === kind);
      const key = kindGroupKey(parentPath, kind);
      const activeLeaf = options.activeSig
        ? kindLeaves.find((leaf) => signatureOf(leaf) === options.activeSig)
        : undefined;
      const isOpen = forceOpen || Boolean(activeLeaf) || !collapsed.has(key);
      out.push({
        type: "kind-group",
        kind,
        parentPath,
        depth,
        sig: `kind-group:${key}`,
        count: kindLeaves.length,
        isOpen,
      });
      if (!isOpen) continue;

      const previewCount = Math.min(
        Math.max(limits.get(key) ?? RESOURCE_PREVIEW_SIZE, RESOURCE_PREVIEW_SIZE),
        kindLeaves.length,
      );
      const visibleLeaves = kindLeaves.slice(0, previewCount);
      if (
        activeLeaf &&
        !visibleLeaves.some((leaf) => signatureOf(leaf) === options.activeSig)
      ) {
        visibleLeaves.push(activeLeaf);
      }
      for (const leaf of visibleLeaves) {
        pushNode(leaf, depth + 1);
      }
      if (visibleLeaves.length < kindLeaves.length) {
        out.push({
          type: "more",
          kind,
          parentPath,
          depth: depth + 1,
          sig: `kind-more:${key}`,
          visibleCount: visibleLeaves.length,
          totalCount: kindLeaves.length,
        });
      }
    }
  };
  visit(nodes, 0, "");
  return out;
}
