type JsonObject = Record<string, unknown>;

const TABLE_ADMIN_OPERATION_IDS = new Set([
  "tablesPostVault",
  "tablesAlterTable",
  "tablesApplyMigration",
]);

const TABLE_REQUEST_COMPONENTS = [
  "CreateTableRequest",
  "AlterTableRequest",
  "TableColumnSpec",
  "TableUniqueKeySpec",
  "TableIndexColumnSpec",
  "TableIndexSpec",
  "TableAlterColumnSpec",
  "TableNamedSpec",
  "TableAddColumnMigration",
  "TableAlterColumnMigration",
  "TableDropColumnMigration",
  "TableRenameColumnMigration",
  "TableAddUniqueKeyMigration",
  "TableDropUniqueKeyMigration",
  "TableAddIndexMigration",
  "TableDropIndexMigration",
] as const;

const RESPONSE_TYPE_BY_SCHEMA = new Map<string, string>([
  ["AkbTableEnvelope", "AkbTableEnvelope"],
  ["AkbTableMigrationEnvelope", "AkbTableMigrationEnvelope"],
  ["AkbTableSchemaEnvelope", "AkbTableSchemaEnvelope"],
  ["AkbVaultTableSchemaEnvelope", "AkbVaultTableSchemaEnvelope"],
  ["AkbTableQueryEnvelope", "AkbTableQueryEnvelope"],
  ["AkbTableSqlEnvelope", "AkbTableSqlEnvelope"],
  ["AkbSqlEnvelope", "AkbSqlEnvelope"],
  ["AkbFileEnvelope", "AkbFileEnvelope"],
  ["AkbDocumentEnvelope", "AkbDocumentEnvelope"],
  ["AkbDocumentWriteEnvelope", "AkbDocumentWriteEnvelope"],
  ["AkbCollectionCreateEnvelope", "AkbCollectionCreateEnvelope"],
  ["AkbCollectionDeleteEnvelope", "AkbCollectionDeleteEnvelope"],
  ["AkbActivityEnvelope", "AkbActivityEnvelope"],
  ["AkbRecentChangesEnvelope", "AkbRecentChangesEnvelope"],
  ["AkbDocumentHistoryEnvelope", "AkbDocumentHistoryEnvelope"],
  ["AkbDocumentDiffEnvelope", "AkbDocumentDiffEnvelope"],
  ["AkbSearchEnvelope", "AkbSearchEnvelope"],
  ["AkbDrillDownEnvelope", "AkbDrillDownEnvelope"],
  ["AkbGrepEnvelope", "AkbGrepEnvelope"],
  ["AkbGraphEnvelope", "AkbGraphEnvelope"],
  ["AkbGraphNeighborsEnvelope", "AkbGraphNeighborsEnvelope"],
  ["AkbGraphOverviewEnvelope", "AkbGraphOverviewEnvelope"],
  ["AkbGraphHealthEnvelope", "AkbGraphHealthEnvelope"],
  ["AkbRelationsEnvelope", "AkbRelationsEnvelope"],
  ["AkbRelationLinkEnvelope", "AkbRelationLinkEnvelope"],
  ["AkbRelationUnlinkEnvelope", "AkbRelationUnlinkEnvelope"],
  ["AkbProvenanceEnvelope", "AkbProvenanceEnvelope"],
]);

export function generateCoreTypes(openapi: unknown): string {
  const spec = expectObject(openapi, "openapi");
  const operations = collectOperations(spec);
  return [
    "/* Generated by akb core OpenAPI codegen. Do not edit manually. */",
    "/* Source: /openapi.json */",
    "",
    "import type { AkbErrorPayload, AkbJsonValue } from \"../index.js\";",
    "import type { AkbOperation } from \"./fetch.js\";",
    "",
    "export type AkbJsonObject = { [key: string]: AkbJsonValue | undefined };",
    "export type AkbJsonObjectArray = AkbJsonObject[];",
    "",
    ...schemaLines(),
    "",
    ...requestSchemaLines(spec),
    "",
    "export interface paths {",
    ...renderPathOperations(operations),
    "}",
    "",
    "export interface operations {",
    ...operations.map((operation) => {
      return `  ${operation.operationId}: paths[${tsLiteral(operation.path)}][${tsLiteral(operation.method)}];`;
    }),
    "}",
    "",
    "export interface components {",
    "  schemas: {",
    "    AkbError: AkbErrorPayload;",
    "    AkbTableEnvelope: AkbTableEnvelope;",
    "    AkbTableMigrationEnvelope: AkbTableMigrationEnvelope;",
    "    AkbTableSchemaEnvelope: AkbTableSchemaEnvelope;",
    "    AkbVaultTableSchemaEnvelope: AkbVaultTableSchemaEnvelope;",
    "    AkbTableQueryEnvelope: AkbTableQueryEnvelope;",
    "    AkbTableSqlEnvelope: AkbTableSqlEnvelope;",
    "    AkbSqlEnvelope: AkbSqlEnvelope;",
    "    AkbFileEnvelope: AkbFileEnvelope;",
    "    AkbDocumentEnvelope: AkbDocumentEnvelope;",
    "    AkbDocumentWriteEnvelope: AkbDocumentWriteEnvelope;",
    "    AkbCollectionSummary: AkbCollectionSummary;",
    "    AkbCollectionCreateEnvelope: AkbCollectionCreateEnvelope;",
    "    AkbCollectionDeleteEnvelope: AkbCollectionDeleteEnvelope;",
    ...TABLE_REQUEST_COMPONENTS.map((name) => `    ${name}: ${name};`),
    "    ActivityFileChange: AkbActivityFileChange;",
    "    ActivityEntry: AkbActivityEntry;",
    "    RecentDocumentChange: AkbRecentDocumentChange;",
    "    DocumentHistoryEntry: AkbDocumentHistoryEntry;",
    "    AkbActivityEnvelope: AkbActivityEnvelope;",
    "    AkbRecentChangesEnvelope: AkbRecentChangesEnvelope;",
    "    AkbDocumentHistoryEnvelope: AkbDocumentHistoryEnvelope;",
    "    AkbDocumentDiffEnvelope: AkbDocumentDiffEnvelope;",
    "    AkbSearchEnvelope: AkbSearchEnvelope;",
    "    AkbDrillDownEnvelope: AkbDrillDownEnvelope;",
    "    AkbGrepEnvelope: AkbGrepEnvelope;",
    "    AkbGraphNode: AkbGraphNode;",
    "    AkbGraphEdge: AkbGraphEdge;",
    "    AkbGraphEnvelope: AkbGraphEnvelope;",
    "    AkbGraphNeighborsEnvelope: AkbGraphNeighborsEnvelope;",
    "    AkbGraphOverviewEnvelope: AkbGraphOverviewEnvelope;",
    "    AkbGraphHealthEnvelope: AkbGraphHealthEnvelope;",
    "    AkbRelation: AkbRelation;",
    "    AkbRelationsEnvelope: AkbRelationsEnvelope;",
    "    AkbRelationLinkEnvelope: AkbRelationLinkEnvelope;",
    "    AkbRelationUnlinkEnvelope: AkbRelationUnlinkEnvelope;",
    "    AkbProvenanceEnvelope: AkbProvenanceEnvelope;",
    "  };",
    "}",
    "",
  ].join("\n");
}

function collectOperations(
  spec: JsonObject,
): Array<{
  path: string;
  method: string;
  operationId: string;
  parameterType: string;
  requestBodyType: string;
  responseType: string;
}> {
  const paths = expectObject(spec.paths, "paths");
  const out: Array<{
    path: string;
    method: string;
    operationId: string;
    parameterType: string;
    requestBodyType: string;
    responseType: string;
  }> = [];
  for (const path of Object.keys(paths).sort()) {
    const pathItem = expectObject(paths[path], `paths.${path}`);
    for (const method of Object.keys(pathItem).sort()) {
      if (!["delete", "get", "patch", "post", "put"].includes(method)) continue;
      const operation = expectObject(pathItem[method], `${path}.${method}`);
      const operationId = stringProp(operation, "operationId") ?? operationIdFrom(path, method);
      out.push({
        path,
        method,
        operationId,
        parameterType: parameterType(path, operation),
        requestBodyType: requestBodyType(method, operationId, operation),
        responseType: responseType(operation),
      });
    }
  }
  return out;
}

function renderPathOperations(
  operations: Array<{
    path: string;
    method: string;
    parameterType: string;
    requestBodyType: string;
    responseType: string;
  }>,
): string[] {
  const byPath = new Map<
    string,
    Array<{
      method: string;
      parameterType: string;
      requestBodyType: string;
      responseType: string;
    }>
  >();
  for (const operation of operations) {
    const methods = byPath.get(operation.path) ?? [];
    methods.push({
      method: operation.method,
      parameterType: operation.parameterType,
      requestBodyType: operation.requestBodyType,
      responseType: operation.responseType,
    });
    byPath.set(operation.path, methods);
  }

  const lines: string[] = [];
  for (const [path, methods] of byPath) {
    lines.push(`  ${tsLiteral(path)}: {`);
    for (const method of methods) {
      lines.push(
        `    ${method.method}: AkbOperation<${tsLiteral(method.method)}, ${tsLiteral(path)}, ${method.parameterType}, ${method.requestBodyType}, ${method.responseType}>;`,
      );
    }
    lines.push("  };");
  }
  return lines;
}

function responseType(operation: JsonObject): string {
  const responses = expectObject(operation.responses, "responses");
  const hasNoContent = Boolean(responses["204"]);
  let jsonType: string | null = null;
  for (const status of ["200", "201", "202"]) {
    const response = responses[status];
    if (!response) continue;
    const schema = expectOptionalObject(expectOptionalObject(response)?.content)?.["application/json"];
    const media = expectOptionalObject(schema);
    const ref = stringProp(expectOptionalObject(media?.schema), "$ref");
    const name = ref?.split("/").at(-1);
    if (name && RESPONSE_TYPE_BY_SCHEMA.has(name)) {
      jsonType = RESPONSE_TYPE_BY_SCHEMA.get(name) ?? "AkbSuccessEnvelope";
      break;
    }
  }
  if (hasNoContent) return jsonType ? `${jsonType} | null` : "null";
  return jsonType ?? "AkbSuccessEnvelope";
}

function parameterType(path: string, operation: JsonObject): string {
  const names = Array.from(path.matchAll(/\{([^}]+)\}/g), (match) => match[1]);
  const parts: string[] = [];
  if (names.length > 0) {
    parts.push(`path: { ${names.map((name) => `${tsKey(name)}: string`).join("; ")} }`);
  }

  const parameters = Array.isArray(operation.parameters) ? operation.parameters : [];
  const headers = parameters
    .map(expectOptionalObject)
    .filter((parameter): parameter is JsonObject => parameter?.in === "header")
    .map((parameter) => {
      const name = stringProp(parameter, "name");
      if (!name) throw new TypeError("Header parameter is missing a name.");
      const optional = parameter.required === true ? "" : "?";
      return `${tsKey(name)}${optional}: ${renderSchema(expectOptionalObject(parameter.schema) ?? {})}`;
    });
  if (headers.length > 0) parts.push(`header: { ${headers.join("; ")} }`);

  return parts.length > 0 ? `{ ${parts.join("; ")} }` : "never";
}

function requestBodyType(method: string, operationId: string, operation: JsonObject): string {
  if (method === "get" || method === "delete") return "never";
  if (!TABLE_ADMIN_OPERATION_IDS.has(operationId)) return "unknown";
  const requestBody = expectOptionalObject(operation.requestBody);
  const content = expectOptionalObject(requestBody?.content);
  const media = expectOptionalObject(content?.["application/json"]);
  const schema = expectOptionalObject(media?.schema);
  return schema ? renderSchema(schema) : "unknown";
}

function requestSchemaLines(spec: JsonObject): string[] {
  const components = expectObject(spec.components, "components");
  const schemas = expectObject(components.schemas, "components.schemas");
  const lines: string[] = [];
  for (const name of TABLE_REQUEST_COMPONENTS) {
    const schema = expectObject(schemas[name], `components.schemas.${name}`);
    lines.push(`export type ${name} = ${renderSchema(schema)};`, "");
  }

  const paths = expectObject(spec.paths, "paths");
  const migrationPath = expectObject(
    paths["/api/v1/tables/{vault}/migrations"],
    "migration path",
  );
  const migrationPost = expectObject(migrationPath.post, "migration post");
  const requestBody = expectObject(migrationPost.requestBody, "migration request body");
  const content = expectObject(requestBody.content, "migration request content");
  const media = expectObject(content["application/json"], "migration JSON request");
  const bodySchema = expectObject(media.schema, "migration request schema");
  const items = expectObject(bodySchema.items, "migration operation items");
  lines.push(`export type TableMigrationOperation = ${renderSchema(items)};`);
  return lines;
}

function renderSchema(schema: JsonObject): string {
  const ref = stringProp(schema, "$ref");
  if (ref) return ref.split("/").at(-1) ?? "unknown";

  const nullable = schema.nullable === true || schemaHasNull(schema);
  const enumValues = Array.isArray(schema.enum) ? schema.enum : null;
  if (enumValues && enumValues.length > 0) {
    const rendered = enumValues.map(renderLiteral).join(" | ");
    return nullable ? `${rendered} | null` : rendered;
  }
  if ("const" in schema) {
    const rendered = renderLiteral(schema.const);
    return nullable ? `${rendered} | null` : rendered;
  }

  const union = Array.isArray(schema.oneOf)
    ? schema.oneOf
    : Array.isArray(schema.anyOf)
      ? schema.anyOf
      : null;
  if (union) {
    return Array.from(
      new Set(
        union.map((item) => renderSchema(expectObject(item, "union schema"))),
      ),
    ).join(" | ");
  }

  if (schema.type === "null") return "null";
  if (schema.type === "string") return nullable ? "string | null" : "string";
  if (schema.type === "integer" || schema.type === "number") {
    return nullable ? "number | null" : "number";
  }
  if (schema.type === "boolean") return nullable ? "boolean | null" : "boolean";
  if (schema.type === "array") {
    const item = renderSchema(expectOptionalObject(schema.items) ?? {});
    const rendered = `${needsParens(item) ? `(${item})` : item}[]`;
    return nullable ? `${rendered} | null` : rendered;
  }
  if (schema.type === "object" || schema.properties || schema.additionalProperties !== undefined) {
    const properties = expectOptionalObject(schema.properties) ?? {};
    const required = new Set(Array.isArray(schema.required) ? schema.required : []);
    const fields = Object.keys(properties).map((name) => {
      const optional = required.has(name) ? "" : "?";
      return `${tsKey(name)}${optional}: ${renderSchema(expectObject(properties[name], name))}`;
    });
    if (schema.additionalProperties === true) {
      fields.push("[key: string]: unknown");
    } else {
      const additional = expectOptionalObject(schema.additionalProperties);
      if (additional) fields.push(`[key: string]: ${renderSchema(additional)}`);
    }
    return fields.length > 0 ? `{ ${fields.join("; ")} }` : "Record<string, unknown>";
  }
  return "unknown";
}

function schemaHasNull(schema: JsonObject): boolean {
  const variants = Array.isArray(schema.anyOf)
    ? schema.anyOf
    : Array.isArray(schema.oneOf)
      ? schema.oneOf
      : [];
  return variants.some((item) => expectOptionalObject(item)?.type === "null");
}

function renderLiteral(value: unknown): string {
  if (
    typeof value === "string"
    || typeof value === "number"
    || typeof value === "boolean"
    || value === null
  ) {
    const literal = JSON.stringify(value);
    if (literal !== undefined) return literal;
  }
  return "unknown";
}

function needsParens(type: string): boolean {
  return type.includes(" | ") || type.includes(" & ");
}

function schemaLines(): string[] {
  return [
    "export interface AkbTableEnvelope {",
    "  kind: \"table\";",
    "  uri?: string;",
    "  vault?: string;",
    "  collection?: string | null;",
    "  name?: string;",
    "  sql_name?: string;",
    "  description?: string | null;",
    "  columns?: AkbJsonObjectArray;",
    "  unique_keys?: AkbJsonObjectArray;",
    "  indexes?: AkbJsonObjectArray;",
    "  row_count?: number;",
    "  deleted?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  total?: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableMigrationEnvelope {",
    "  kind: \"table_migration\";",
    "  vault: string;",
    "  idempotency_key: string;",
    "  checksum: string;",
    "  applied: boolean;",
    "  operations: number;",
    "  results: AkbJsonObjectArray;",
    "  id?: string;",
    "  applied_at?: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableSchemaEnvelope {",
    "  kind: \"table_schema\";",
    "  vault: string;",
    "  name: string;",
    "  columns: AkbJsonObjectArray;",
    "  pg_types: Record<string, string>;",
    "  drift: AkbJsonObject;",
    "  uri?: string;",
    "  collection?: string | null;",
    "  table?: string;",
    "  sql_name?: string;",
    "  unique_keys?: AkbJsonObjectArray;",
    "  indexes?: AkbJsonObjectArray;",
    "  system_columns?: string[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbVaultTableSchemaEnvelope {",
    "  kind: \"vault_table_schema\";",
    "  vault: string;",
    "  tables: AkbTableSchemaEnvelope[];",
    "  total: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableQueryEnvelope<Row = AkbJsonObject> {",
    "  kind: \"table_query\";",
    "  columns: string[];",
    "  items: Row[];",
    "  total: number;",
    "  vault?: string;",
    "  table?: string;",
    "  vaults?: string[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableSqlEnvelope {",
    "  kind: \"table_sql\";",
    "  vaults: string[];",
    "  result: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbSqlEnvelope = AkbTableQueryEnvelope | AkbTableSqlEnvelope;",
    "",
    "export interface AkbFileEnvelope {",
    "  kind: \"file\";",
    "  uri?: string;",
    "  id?: string;",
    "  vault?: string;",
    "  collection?: string | null;",
    "  name?: string;",
    "  mime_type?: string;",
    "  size_bytes?: number;",
    "  description?: string | null;",
    "  upload_url?: string;",
    "  download_url?: string;",
    "  deleted?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  total?: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDocumentEnvelope {",
    "  kind: \"document\";",
    "  uri?: string;",
    "  vault?: string;",
    "  path?: string;",
    "  title?: string;",
    "  type?: string;",
    "  status?: string;",
    "  summary?: string | null;",
    "  domain?: string | null;",
    "  created_by?: string | null;",
    "  created_by_name?: string | null;",
    "  created_at?: string;",
    "  updated_at?: string;",
    "  current_commit?: string | null;",
    "  content_hash?: string | null;",
    "  hash_algorithm?: string | null;",
    "  tags?: string[];",
    "  content?: string | null;",
    "  is_public?: boolean;",
    "  public_slug?: string | null;",
    "  metadata_is_current?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  hint?: string | null;",
    "  deleted?: boolean;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDocumentWriteEnvelope {",
    "  kind: \"document_write\";",
    "  uri: string;",
    "  vault: string;",
    "  path: string;",
    "  commit_hash: string;",
    "  chunks_indexed: number;",
    "  entities_found: number;",
    "  current_commit?: string | null;",
    "  previous_commit?: string | null;",
    "  content_hash?: string | null;",
    "  previous_content_hash?: string | null;",
    "  hash_algorithm?: string | null;",
    "  action?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbSearchResult {",
    "  source_type: string;",
    "  uri: string;",
    "  vault: string;",
    "  path: string;",
    "  title: string;",
    "  collection?: string | null;",
    "  doc_type?: string | null;",
    "  summary?: string | null;",
    "  tags: string[];",
    "  score: number;",
    "  matched_section?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbSearchEnvelope {",
    "  kind: \"search\";",
    "  query: string;",
    "  total: number;",
    "  returned: number;",
    "  total_matches: number;",
    "  results: AkbSearchResult[];",
    "  truncated?: boolean;",
    "  hint?: string | null;",
    "  degraded?: boolean;",
    "  degradation_reason?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDrillDownSection {",
    "  chunk_index: number;",
    "  section_path?: string | null;",
    "  content?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDrillDownEnvelope {",
    "  kind: \"drill_down\";",
    "  uri: string;",
    "  sections: AkbDrillDownSection[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGrepMatch {",
    "  text: string;",
    "  section?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGrepResult {",
    "  uri: string;",
    "  vault: string;",
    "  path: string;",
    "  title: string;",
    "  matches?: AkbGrepMatch[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGrepEnvelope {",
    "  kind: \"grep\";",
    "  pattern: string;",
    "  regex: boolean;",
    "  error?: string | null;",
    "  returned_docs?: number | null;",
    "  returned_matches?: number | null;",
    "  total_docs?: number | null;",
    "  total_matches?: number | null;",
    "  truncated?: boolean | null;",
    "  hint?: string | null;",
    "  results?: AkbGrepResult[] | null;",
    "  by_doc?: Record<string, number> | null;",
    "  n_files?: number | null;",
    "  files?: string[] | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbCollectionSummary {",
    "  path: string;",
    "  name: string;",
    "  summary: string | null;",
    "  doc_count: number;",
    "}",
    "",
    "export interface AkbCollectionCreateEnvelope {",
    "  kind: \"collection_create\";",
    "  ok: true;",
    "  created: boolean;",
    "  collection: AkbCollectionSummary;",
    "}",
    "",
    "export interface AkbCollectionDeleteEnvelope {",
    "  kind: \"collection_delete\";",
    "  ok: true;",
    "  collection: string;",
    "  deleted_docs: number;",
    "  deleted_files: number;",
    "  deleted_sub_collections: number;",
    "  deleted_tables: number;",
    "}",
    "",
    "export interface AkbActivityFileChange {",
    "  path: string;",
    "  change: \"added\" | \"deleted\" | \"modified\";",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbActivityEntry {",
    "  hash: string;",
    "  subject: string;",
    "  author: string;",
    "  date: string;",
    "  action: string;",
    "  summary: string;",
    "  agent: string;",
    "  files: AkbActivityFileChange[];",
    "  author_name?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRecentDocumentChange {",
    "  doc_id: string;",
    "  vault: string;",
    "  path: string;",
    "  title: string;",
    "  type: string;",
    "  commit: string | null;",
    "  changed_at: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDocumentHistoryEntry {",
    "  hash: string;",
    "  message: string;",
    "  author: string;",
    "  date: string;",
    "  author_name?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbActivityEnvelope {",
    "  kind: \"activity\";",
    "  vault: string;",
    "  total: number;",
    "  activity: AkbActivityEntry[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRecentChangesEnvelope {",
    "  kind: \"recent_changes\";",
    "  changes: AkbRecentDocumentChange[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDocumentHistoryEnvelope {",
    "  kind: \"document_history\";",
    "  uri: string;",
    "  history: AkbDocumentHistoryEntry[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDocumentDiffEnvelope {",
    "  kind: \"document_diff\";",
    "  file: string;",
    "  commit: string;",
    "  type: \"added\" | \"deleted\" | \"modified\" | \"unknown\" | \"unchanged\";",
    "  diff: string;",
    "  error?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphNode {",
    "  uri: string;",
    "  name: string;",
    "  resource_type: \"doc\" | \"table\" | \"file\";",
    "  depth?: number | null;",
    "  degree?: number | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphEdge {",
    "  source: string;",
    "  target: string;",
    "  relation: AkbRelationType;",
    "  kind: \"implicit\" | \"explicit\";",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphNeighborsEnvelope {",
    "  kind: \"graph_neighbors\";",
    "  nodes: AkbGraphNode[];",
    "  edges: AkbGraphEdge[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphOverviewEnvelope {",
    "  kind: \"graph_overview\";",
    "  nodes: AkbGraphNode[];",
    "  edges: AkbGraphEdge[];",
    "  nodes_total: number;",
    "  edges_total: number;",
    "  returned: number;",
    "  truncated: boolean;",
    "  orphans_returned: number;",
    "  orphans_truncated: boolean;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphHealthEnvelope {",
    "  kind: \"graph_health\";",
    "  hubs: AkbGraphNode[];",
    "  orphans: {",
    "    count: number;",
    "    sample: AkbGraphNode[];",
    "    [key: string]: unknown;",
    "  };",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbGraphEnvelope = AkbGraphNeighborsEnvelope | AkbGraphOverviewEnvelope;",
    "",
    "export type AkbWritableRelationType =",
    "  | \"depends_on\"",
    "  | \"related_to\"",
    "  | \"implements\"",
    "  | \"references\"",
    "  | \"attached_to\"",
    "  | \"derived_from\";",
    "",
    "export type AkbRelationType = AkbWritableRelationType | \"links_to\";",
    "",
    "export interface AkbRelation {",
    "  direction: \"incoming\" | \"outgoing\";",
    "  relation: AkbRelationType;",
    "  uri: string;",
    "  resource_type: \"doc\" | \"table\" | \"file\";",
    "  name?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRelationsEnvelope {",
    "  kind: \"relations\";",
    "  uri: string;",
    "  relations: AkbRelation[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRelationLinkEnvelope {",
    "  kind: \"relation_link\";",
    "  linked: boolean;",
    "  source: string;",
    "  target: string;",
    "  relation: AkbWritableRelationType;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRelationUnlinkEnvelope {",
    "  kind: \"relation_unlink\";",
    "  unlinked: number;",
    "  source: string;",
    "  target: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbProvenanceEnvelope {",
    "  kind: \"provenance\";",
    "  doc_id: string;",
    "  title: string;",
    "  path: string;",
    "  vault: string;",
    "  uri: string;",
    "  created_by: string | null;",
    "  created_at: string | null;",
    "  updated_at: string | null;",
    "  current_commit: string | null;",
    "  relations: AkbRelation[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbSuccessEnvelope =",
    "  | AkbTableEnvelope",
    "  | AkbTableMigrationEnvelope",
    "  | AkbTableSchemaEnvelope",
    "  | AkbVaultTableSchemaEnvelope",
    "  | AkbTableQueryEnvelope",
    "  | AkbTableSqlEnvelope",
    "  | AkbFileEnvelope",
    "  | AkbDocumentEnvelope",
    "  | AkbDocumentWriteEnvelope",
    "  | AkbSearchEnvelope",
    "  | AkbDrillDownEnvelope",
    "  | AkbGrepEnvelope",
    "  | AkbCollectionCreateEnvelope",
    "  | AkbCollectionDeleteEnvelope",
    "  | AkbActivityEnvelope",
    "  | AkbRecentChangesEnvelope",
    "  | AkbDocumentHistoryEnvelope",
    "  | AkbDocumentDiffEnvelope",
    "  | AkbGraphNeighborsEnvelope",
    "  | AkbGraphOverviewEnvelope",
    "  | AkbGraphHealthEnvelope",
    "  | AkbRelationsEnvelope",
    "  | AkbRelationLinkEnvelope",
    "  | AkbRelationUnlinkEnvelope",
    "  | AkbProvenanceEnvelope;",
  ];
}

function expectObject(value: unknown, label: string): JsonObject {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as JsonObject;
  }
  throw new TypeError(`${label} must be an object.`);
}

function expectOptionalObject(value: unknown): JsonObject | null {
  if (value === null || value === undefined) return null;
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as JsonObject)
    : null;
}

function stringProp(object: JsonObject | null, key: string): string | null {
  const value = object?.[key];
  return typeof value === "string" && value.length > 0 ? value : null;
}

function operationIdFrom(path: string, method: string): string {
  const words = path.replace(/^\/api\/v1\//, "").match(/[A-Za-z0-9]+/g) ?? ["api"];
  const pascal = words.map((word) => word[0].toUpperCase() + word.slice(1)).join("");
  return `${method}${pascal}`;
}

function tsLiteral(value: string): string {
  return JSON.stringify(value);
}

function tsKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : tsLiteral(key);
}
