type JsonObject = Record<string, unknown>;

const RESPONSE_TYPE_BY_SCHEMA = new Map<string, string>([
  ["AkbTableEnvelope", "AkbTableEnvelope"],
  ["AkbTableMigrationEnvelope", "AkbTableMigrationEnvelope"],
  ["AkbTableSchemaEnvelope", "AkbTableSchemaEnvelope"],
  ["AkbVaultTableSchemaEnvelope", "AkbVaultTableSchemaEnvelope"],
  ["AkbTableQueryEnvelope", "AkbTableQueryEnvelope"],
  ["AkbTableSqlEnvelope", "AkbTableSqlEnvelope"],
  ["AkbSqlEnvelope", "AkbSqlEnvelope"],
  ["AkbFileEnvelope", "AkbFileEnvelope"],
  ["AkbDocumentEnvelope", "AkbDocumentEnvelope"],
  ["AkbDocumentWriteEnvelope", "AkbDocumentWriteEnvelope"],
  ["AkbSearchEnvelope", "AkbSearchEnvelope"],
  ["AkbDrillDownEnvelope", "AkbDrillDownEnvelope"],
  ["AkbGrepEnvelope", "AkbGrepEnvelope"],
  ["AkbGraphEnvelope", "AkbGraphEnvelope"],
  ["AkbGraphNeighborsEnvelope", "AkbGraphNeighborsEnvelope"],
  ["AkbGraphOverviewEnvelope", "AkbGraphOverviewEnvelope"],
  ["AkbGraphHealthEnvelope", "AkbGraphHealthEnvelope"],
  ["AkbRelationsEnvelope", "AkbRelationsEnvelope"],
  ["AkbRelationLinkEnvelope", "AkbRelationLinkEnvelope"],
  ["AkbRelationUnlinkEnvelope", "AkbRelationUnlinkEnvelope"],
  ["AkbProvenanceEnvelope", "AkbProvenanceEnvelope"],
]);

export function generateCoreTypes(openapi: unknown): string {
  const spec = expectObject(openapi, "openapi");
  const operations = collectOperations(spec);
  return [
    "/* Generated by akb core OpenAPI codegen. Do not edit manually. */",
    "/* Source: /openapi.json */",
    "",
    "import type { AkbErrorPayload, AkbJsonValue } from \"../index.js\";",
    "import type { AkbOperation } from \"./fetch.js\";",
    "",
    "export type AkbJsonObject = { [key: string]: AkbJsonValue | undefined };",
    "export type AkbJsonObjectArray = AkbJsonObject[];",
    "",
    ...schemaLines(),
    "",
    "export interface paths {",
    ...renderPathOperations(operations),
    "}",
    "",
    "export interface operations {",
    ...operations.map((operation) => {
      return `  ${operation.operationId}: paths[${tsLiteral(operation.path)}][${tsLiteral(operation.method)}];`;
    }),
    "}",
    "",
    "export interface components {",
    "  schemas: {",
    "    AkbError: AkbErrorPayload;",
    "    AkbTableEnvelope: AkbTableEnvelope;",
    "    AkbTableMigrationEnvelope: AkbTableMigrationEnvelope;",
    "    AkbTableSchemaEnvelope: AkbTableSchemaEnvelope;",
    "    AkbVaultTableSchemaEnvelope: AkbVaultTableSchemaEnvelope;",
    "    AkbTableQueryEnvelope: AkbTableQueryEnvelope;",
    "    AkbTableSqlEnvelope: AkbTableSqlEnvelope;",
    "    AkbSqlEnvelope: AkbSqlEnvelope;",
    "    AkbFileEnvelope: AkbFileEnvelope;",
    "    AkbDocumentEnvelope: AkbDocumentEnvelope;",
    "    AkbDocumentWriteEnvelope: AkbDocumentWriteEnvelope;",
    "    AkbSearchEnvelope: AkbSearchEnvelope;",
    "    AkbDrillDownEnvelope: AkbDrillDownEnvelope;",
    "    AkbGrepEnvelope: AkbGrepEnvelope;",
    "    AkbGraphNode: AkbGraphNode;",
    "    AkbGraphEdge: AkbGraphEdge;",
    "    AkbGraphEnvelope: AkbGraphEnvelope;",
    "    AkbGraphNeighborsEnvelope: AkbGraphNeighborsEnvelope;",
    "    AkbGraphOverviewEnvelope: AkbGraphOverviewEnvelope;",
    "    AkbGraphHealthEnvelope: AkbGraphHealthEnvelope;",
    "    AkbRelation: AkbRelation;",
    "    AkbRelationsEnvelope: AkbRelationsEnvelope;",
    "    AkbRelationLinkEnvelope: AkbRelationLinkEnvelope;",
    "    AkbRelationUnlinkEnvelope: AkbRelationUnlinkEnvelope;",
    "    AkbProvenanceEnvelope: AkbProvenanceEnvelope;",
    "  };",
    "}",
    "",
  ].join("\n");
}

function collectOperations(
  spec: JsonObject,
): Array<{ path: string; method: string; operationId: string; responseType: string }> {
  const paths = expectObject(spec.paths, "paths");
  const out: Array<{ path: string; method: string; operationId: string; responseType: string }> = [];
  for (const path of Object.keys(paths).sort()) {
    const pathItem = expectObject(paths[path], `paths.${path}`);
    for (const method of Object.keys(pathItem).sort()) {
      if (!["delete", "get", "patch", "post", "put"].includes(method)) continue;
      const operation = expectObject(pathItem[method], `${path}.${method}`);
      const operationId = stringProp(operation, "operationId") ?? operationIdFrom(path, method);
      out.push({
        path,
        method,
        operationId,
        responseType: responseType(operation),
      });
    }
  }
  return out;
}

function renderPathOperations(
  operations: Array<{ path: string; method: string; responseType: string }>,
): string[] {
  const byPath = new Map<string, Array<{ method: string; responseType: string }>>();
  for (const operation of operations) {
    const methods = byPath.get(operation.path) ?? [];
    methods.push({ method: operation.method, responseType: operation.responseType });
    byPath.set(operation.path, methods);
  }

  const lines: string[] = [];
  for (const [path, methods] of byPath) {
    lines.push(`  ${tsLiteral(path)}: {`);
    for (const method of methods) {
      lines.push(
        `    ${method.method}: AkbOperation<${tsLiteral(method.method)}, ${tsLiteral(path)}, ${pathParameterType(path)}, ${requestBodyType(method.method)}, ${method.responseType}>;`,
      );
    }
    lines.push("  };");
  }
  return lines;
}

function responseType(operation: JsonObject): string {
  const responses = expectObject(operation.responses, "responses");
  const hasNoContent = Boolean(responses["204"]);
  let jsonType: string | null = null;
  for (const status of ["200", "201", "202"]) {
    const response = responses[status];
    if (!response) continue;
    const schema = expectOptionalObject(expectOptionalObject(response)?.content)?.["application/json"];
    const media = expectOptionalObject(schema);
    const ref = stringProp(expectOptionalObject(media?.schema), "$ref");
    const name = ref?.split("/").at(-1);
    if (name && RESPONSE_TYPE_BY_SCHEMA.has(name)) {
      jsonType = RESPONSE_TYPE_BY_SCHEMA.get(name) ?? "AkbSuccessEnvelope";
      break;
    }
  }
  if (hasNoContent) return jsonType ? `${jsonType} | null` : "null";
  return jsonType ?? "AkbSuccessEnvelope";
}

function pathParameterType(path: string): string {
  const names = Array.from(path.matchAll(/\{([^}]+)\}/g), (match) => match[1]);
  if (names.length === 0) return "never";
  return `{ path: { ${names.map((name) => `${tsKey(name)}: string`).join("; ")} } }`;
}

function requestBodyType(method: string): string {
  return method === "get" || method === "delete" ? "never" : "unknown";
}

function schemaLines(): string[] {
  return [
    "export interface AkbTableEnvelope {",
    "  kind: \"table\";",
    "  uri?: string;",
    "  vault?: string;",
    "  collection?: string | null;",
    "  name?: string;",
    "  sql_name?: string;",
    "  description?: string | null;",
    "  columns?: AkbJsonObjectArray;",
    "  unique_keys?: AkbJsonObjectArray;",
    "  indexes?: AkbJsonObjectArray;",
    "  row_count?: number;",
    "  deleted?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  total?: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableMigrationEnvelope {",
    "  kind: \"table_migration\";",
    "  vault: string;",
    "  idempotency_key: string;",
    "  checksum: string;",
    "  applied: boolean;",
    "  operations: number;",
    "  results: AkbJsonObjectArray;",
    "  id?: string;",
    "  applied_at?: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableSchemaEnvelope {",
    "  kind: \"table_schema\";",
    "  vault: string;",
    "  name: string;",
    "  columns: AkbJsonObjectArray;",
    "  pg_types: Record<string, string>;",
    "  drift: AkbJsonObject;",
    "  uri?: string;",
    "  collection?: string | null;",
    "  table?: string;",
    "  sql_name?: string;",
    "  unique_keys?: AkbJsonObjectArray;",
    "  indexes?: AkbJsonObjectArray;",
    "  system_columns?: string[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbVaultTableSchemaEnvelope {",
    "  kind: \"vault_table_schema\";",
    "  vault: string;",
    "  tables: AkbTableSchemaEnvelope[];",
    "  total: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableQueryEnvelope<Row = AkbJsonObject> {",
    "  kind: \"table_query\";",
    "  columns: string[];",
    "  items: Row[];",
    "  total: number;",
    "  vault?: string;",
    "  table?: string;",
    "  vaults?: string[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableSqlEnvelope {",
    "  kind: \"table_sql\";",
    "  vaults: string[];",
    "  result: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbSqlEnvelope = AkbTableQueryEnvelope | AkbTableSqlEnvelope;",
    "",
    "export interface AkbFileEnvelope {",
    "  kind: \"file\";",
    "  uri?: string;",
    "  id?: string;",
    "  vault?: string;",
    "  collection?: string | null;",
    "  name?: string;",
    "  mime_type?: string;",
    "  size_bytes?: number;",
    "  description?: string | null;",
    "  upload_url?: string;",
    "  download_url?: string;",
    "  deleted?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  total?: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDocumentEnvelope {",
    "  kind: \"document\";",
    "  uri?: string;",
    "  vault?: string;",
    "  path?: string;",
    "  title?: string;",
    "  type?: string;",
    "  status?: string;",
    "  summary?: string | null;",
    "  domain?: string | null;",
    "  created_by?: string | null;",
    "  created_by_name?: string | null;",
    "  created_at?: string;",
    "  updated_at?: string;",
    "  current_commit?: string | null;",
    "  content_hash?: string | null;",
    "  hash_algorithm?: string | null;",
    "  tags?: string[];",
    "  content?: string | null;",
    "  is_public?: boolean;",
    "  public_slug?: string | null;",
    "  metadata_is_current?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  hint?: string | null;",
    "  deleted?: boolean;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDocumentWriteEnvelope {",
    "  kind: \"document_write\";",
    "  uri: string;",
    "  vault: string;",
    "  path: string;",
    "  commit_hash: string;",
    "  chunks_indexed: number;",
    "  entities_found: number;",
    "  current_commit?: string | null;",
    "  previous_commit?: string | null;",
    "  content_hash?: string | null;",
    "  previous_content_hash?: string | null;",
    "  hash_algorithm?: string | null;",
    "  action?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbSearchResult {",
    "  source_type: string;",
    "  uri: string;",
    "  vault: string;",
    "  path: string;",
    "  title: string;",
    "  collection?: string | null;",
    "  doc_type?: string | null;",
    "  summary?: string | null;",
    "  tags: string[];",
    "  score: number;",
    "  matched_section?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbSearchEnvelope {",
    "  kind: \"search\";",
    "  query: string;",
    "  total: number;",
    "  returned: number;",
    "  total_matches: number;",
    "  results: AkbSearchResult[];",
    "  truncated?: boolean;",
    "  hint?: string | null;",
    "  degraded?: boolean;",
    "  degradation_reason?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDrillDownSection {",
    "  chunk_index: number;",
    "  section_path?: string | null;",
    "  content?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbDrillDownEnvelope {",
    "  kind: \"drill_down\";",
    "  uri: string;",
    "  sections: AkbDrillDownSection[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGrepMatch {",
    "  text: string;",
    "  section?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGrepResult {",
    "  uri: string;",
    "  vault: string;",
    "  path: string;",
    "  title: string;",
    "  matches?: AkbGrepMatch[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGrepEnvelope {",
    "  kind: \"grep\";",
    "  pattern: string;",
    "  regex: boolean;",
    "  error?: string | null;",
    "  returned_docs?: number | null;",
    "  returned_matches?: number | null;",
    "  total_docs?: number | null;",
    "  total_matches?: number | null;",
    "  truncated?: boolean | null;",
    "  hint?: string | null;",
    "  results?: AkbGrepResult[] | null;",
    "  by_doc?: Record<string, number> | null;",
    "  n_files?: number | null;",
    "  files?: string[] | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphNode {",
    "  uri: string;",
    "  name: string;",
    "  resource_type: \"doc\" | \"table\" | \"file\";",
    "  depth?: number | null;",
    "  degree?: number | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphEdge {",
    "  source: string;",
    "  target: string;",
    "  relation: AkbRelationType;",
    "  kind: \"implicit\" | \"explicit\";",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphNeighborsEnvelope {",
    "  kind: \"graph_neighbors\";",
    "  nodes: AkbGraphNode[];",
    "  edges: AkbGraphEdge[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphOverviewEnvelope {",
    "  kind: \"graph_overview\";",
    "  nodes: AkbGraphNode[];",
    "  edges: AkbGraphEdge[];",
    "  nodes_total: number;",
    "  edges_total: number;",
    "  returned: number;",
    "  truncated: boolean;",
    "  orphans_returned: number;",
    "  orphans_truncated: boolean;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbGraphHealthEnvelope {",
    "  kind: \"graph_health\";",
    "  hubs: AkbGraphNode[];",
    "  orphans: {",
    "    count: number;",
    "    sample: AkbGraphNode[];",
    "    [key: string]: unknown;",
    "  };",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbGraphEnvelope = AkbGraphNeighborsEnvelope | AkbGraphOverviewEnvelope;",
    "",
    "export type AkbWritableRelationType =",
    "  | \"depends_on\"",
    "  | \"related_to\"",
    "  | \"implements\"",
    "  | \"references\"",
    "  | \"attached_to\"",
    "  | \"derived_from\";",
    "",
    "export type AkbRelationType = AkbWritableRelationType | \"links_to\";",
    "",
    "export interface AkbRelation {",
    "  direction: \"incoming\" | \"outgoing\";",
    "  relation: AkbRelationType;",
    "  uri: string;",
    "  resource_type: \"doc\" | \"table\" | \"file\";",
    "  name?: string | null;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRelationsEnvelope {",
    "  kind: \"relations\";",
    "  uri: string;",
    "  relations: AkbRelation[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRelationLinkEnvelope {",
    "  kind: \"relation_link\";",
    "  linked: boolean;",
    "  source: string;",
    "  target: string;",
    "  relation: AkbWritableRelationType;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbRelationUnlinkEnvelope {",
    "  kind: \"relation_unlink\";",
    "  unlinked: number;",
    "  source: string;",
    "  target: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbProvenanceEnvelope {",
    "  kind: \"provenance\";",
    "  doc_id: string;",
    "  title: string;",
    "  path: string;",
    "  vault: string;",
    "  uri: string;",
    "  created_by: string | null;",
    "  created_at: string | null;",
    "  updated_at: string | null;",
    "  current_commit: string | null;",
    "  relations: AkbRelation[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbSuccessEnvelope =",
    "  | AkbTableEnvelope",
    "  | AkbTableMigrationEnvelope",
    "  | AkbTableSchemaEnvelope",
    "  | AkbVaultTableSchemaEnvelope",
    "  | AkbTableQueryEnvelope",
    "  | AkbTableSqlEnvelope",
    "  | AkbFileEnvelope",
    "  | AkbDocumentEnvelope",
    "  | AkbDocumentWriteEnvelope",
    "  | AkbSearchEnvelope",
    "  | AkbDrillDownEnvelope",
    "  | AkbGrepEnvelope",
    "  | AkbGraphNeighborsEnvelope",
    "  | AkbGraphOverviewEnvelope",
    "  | AkbGraphHealthEnvelope",
    "  | AkbRelationsEnvelope",
    "  | AkbRelationLinkEnvelope",
    "  | AkbRelationUnlinkEnvelope",
    "  | AkbProvenanceEnvelope;",
  ];
}

function expectObject(value: unknown, label: string): JsonObject {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as JsonObject;
  }
  throw new TypeError(`${label} must be an object.`);
}

function expectOptionalObject(value: unknown): JsonObject | null {
  if (value === null || value === undefined) return null;
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as JsonObject)
    : null;
}

function stringProp(object: JsonObject | null, key: string): string | null {
  const value = object?.[key];
  return typeof value === "string" && value.length > 0 ? value : null;
}

function operationIdFrom(path: string, method: string): string {
  const words = path.replace(/^\/api\/v1\//, "").match(/[A-Za-z0-9]+/g) ?? ["api"];
  const pascal = words.map((word) => word[0].toUpperCase() + word.slice(1)).join("");
  return `${method}${pascal}`;
}

function tsLiteral(value: string): string {
  return JSON.stringify(value);
}

function tsKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : tsLiteral(key);
}
