type JsonObject = Record<string, unknown>;

const RESPONSE_TYPE_BY_SCHEMA = new Map<string, string>([
  ["AkbTableEnvelope", "AkbTableEnvelope"],
  ["AkbTableMigrationEnvelope", "AkbTableMigrationEnvelope"],
  ["AkbTableSchemaEnvelope", "AkbTableSchemaEnvelope"],
  ["AkbVaultTableSchemaEnvelope", "AkbVaultTableSchemaEnvelope"],
  ["AkbTableQueryEnvelope", "AkbTableQueryEnvelope"],
  ["AkbTableSqlEnvelope", "AkbTableSqlEnvelope"],
  ["AkbSqlEnvelope", "AkbSqlEnvelope"],
  ["AkbFileEnvelope", "AkbFileEnvelope"],
]);

export function generateCoreTypes(openapi: unknown): string {
  const spec = expectObject(openapi, "openapi");
  const operations = collectOperations(spec);
  return [
    "/* Generated by akb core OpenAPI codegen. Do not edit manually. */",
    "/* Source: /openapi.json */",
    "",
    "import type { AkbErrorPayload, AkbJsonValue } from \"../index.js\";",
    "import type { AkbOperation } from \"./fetch.js\";",
    "",
    "export type AkbJsonObject = { [key: string]: AkbJsonValue | undefined };",
    "export type AkbJsonObjectArray = AkbJsonObject[];",
    "",
    ...schemaLines(),
    "",
    "export interface paths {",
    ...renderPathOperations(operations),
    "}",
    "",
    "export interface operations {",
    ...operations.map((operation) => {
      return `  ${operation.operationId}: paths[${tsLiteral(operation.path)}][${tsLiteral(operation.method)}];`;
    }),
    "}",
    "",
    "export interface components {",
    "  schemas: {",
    "    AkbError: AkbErrorPayload;",
    "    AkbTableEnvelope: AkbTableEnvelope;",
    "    AkbTableMigrationEnvelope: AkbTableMigrationEnvelope;",
    "    AkbTableSchemaEnvelope: AkbTableSchemaEnvelope;",
    "    AkbVaultTableSchemaEnvelope: AkbVaultTableSchemaEnvelope;",
    "    AkbTableQueryEnvelope: AkbTableQueryEnvelope;",
    "    AkbTableSqlEnvelope: AkbTableSqlEnvelope;",
    "    AkbSqlEnvelope: AkbSqlEnvelope;",
    "    AkbFileEnvelope: AkbFileEnvelope;",
    "  };",
    "}",
    "",
  ].join("\n");
}

function collectOperations(
  spec: JsonObject,
): Array<{ path: string; method: string; operationId: string; responseType: string }> {
  const paths = expectObject(spec.paths, "paths");
  const out: Array<{ path: string; method: string; operationId: string; responseType: string }> = [];
  for (const path of Object.keys(paths).sort()) {
    const pathItem = expectObject(paths[path], `paths.${path}`);
    for (const method of Object.keys(pathItem).sort()) {
      if (!["delete", "get", "patch", "post", "put"].includes(method)) continue;
      const operation = expectObject(pathItem[method], `${path}.${method}`);
      const operationId = stringProp(operation, "operationId") ?? operationIdFrom(path, method);
      out.push({
        path,
        method,
        operationId,
        responseType: responseType(operation),
      });
    }
  }
  return out;
}

function renderPathOperations(
  operations: Array<{ path: string; method: string; responseType: string }>,
): string[] {
  const byPath = new Map<string, Array<{ method: string; responseType: string }>>();
  for (const operation of operations) {
    const methods = byPath.get(operation.path) ?? [];
    methods.push({ method: operation.method, responseType: operation.responseType });
    byPath.set(operation.path, methods);
  }

  const lines: string[] = [];
  for (const [path, methods] of byPath) {
    lines.push(`  ${tsLiteral(path)}: {`);
    for (const method of methods) {
      lines.push(
        `    ${method.method}: AkbOperation<${tsLiteral(method.method)}, ${tsLiteral(path)}, ${pathParameterType(path)}, ${requestBodyType(method.method)}, ${method.responseType}>;`,
      );
    }
    lines.push("  };");
  }
  return lines;
}

function responseType(operation: JsonObject): string {
  const responses = expectObject(operation.responses, "responses");
  const hasNoContent = Boolean(responses["204"]);
  let jsonType: string | null = null;
  for (const status of ["200", "201", "202"]) {
    const response = responses[status];
    if (!response) continue;
    const schema = expectOptionalObject(expectOptionalObject(response)?.content)?.["application/json"];
    const media = expectOptionalObject(schema);
    const ref = stringProp(expectOptionalObject(media?.schema), "$ref");
    const name = ref?.split("/").at(-1);
    if (name && RESPONSE_TYPE_BY_SCHEMA.has(name)) {
      jsonType = RESPONSE_TYPE_BY_SCHEMA.get(name) ?? "AkbSuccessEnvelope";
      break;
    }
  }
  if (hasNoContent) return jsonType ? `${jsonType} | null` : "null";
  return jsonType ?? "AkbSuccessEnvelope";
}

function pathParameterType(path: string): string {
  const names = Array.from(path.matchAll(/\{([^}]+)\}/g), (match) => match[1]);
  if (names.length === 0) return "never";
  return `{ path: { ${names.map((name) => `${tsKey(name)}: string`).join("; ")} } }`;
}

function requestBodyType(method: string): string {
  return method === "get" || method === "delete" ? "never" : "unknown";
}

function schemaLines(): string[] {
  return [
    "export interface AkbTableEnvelope {",
    "  kind: \"table\";",
    "  uri?: string;",
    "  vault?: string;",
    "  collection?: string | null;",
    "  name?: string;",
    "  sql_name?: string;",
    "  description?: string | null;",
    "  columns?: AkbJsonObjectArray;",
    "  unique_keys?: AkbJsonObjectArray;",
    "  indexes?: AkbJsonObjectArray;",
    "  row_count?: number;",
    "  deleted?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  total?: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableMigrationEnvelope {",
    "  kind: \"table_migration\";",
    "  vault: string;",
    "  idempotency_key: string;",
    "  checksum: string;",
    "  applied: boolean;",
    "  operations: number;",
    "  results: AkbJsonObjectArray;",
    "  id?: string;",
    "  applied_at?: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableSchemaEnvelope {",
    "  kind: \"table_schema\";",
    "  vault: string;",
    "  name: string;",
    "  columns: AkbJsonObjectArray;",
    "  pg_types: Record<string, string>;",
    "  drift: AkbJsonObject;",
    "  uri?: string;",
    "  collection?: string | null;",
    "  table?: string;",
    "  sql_name?: string;",
    "  unique_keys?: AkbJsonObjectArray;",
    "  indexes?: AkbJsonObjectArray;",
    "  system_columns?: string[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbVaultTableSchemaEnvelope {",
    "  kind: \"vault_table_schema\";",
    "  vault: string;",
    "  tables: AkbTableSchemaEnvelope[];",
    "  total: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableQueryEnvelope<Row = AkbJsonObject> {",
    "  kind: \"table_query\";",
    "  columns: string[];",
    "  items: Row[];",
    "  total: number;",
    "  vault?: string;",
    "  table?: string;",
    "  vaults?: string[];",
    "  [key: string]: unknown;",
    "}",
    "",
    "export interface AkbTableSqlEnvelope {",
    "  kind: \"table_sql\";",
    "  vaults: string[];",
    "  result: string;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbSqlEnvelope = AkbTableQueryEnvelope | AkbTableSqlEnvelope;",
    "",
    "export interface AkbFileEnvelope {",
    "  kind: \"file\";",
    "  uri?: string;",
    "  id?: string;",
    "  vault?: string;",
    "  collection?: string | null;",
    "  name?: string;",
    "  mime_type?: string;",
    "  size_bytes?: number;",
    "  description?: string | null;",
    "  upload_url?: string;",
    "  download_url?: string;",
    "  deleted?: boolean;",
    "  items?: AkbJsonObjectArray;",
    "  total?: number;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AkbSuccessEnvelope =",
    "  | AkbTableEnvelope",
    "  | AkbTableMigrationEnvelope",
    "  | AkbTableSchemaEnvelope",
    "  | AkbVaultTableSchemaEnvelope",
    "  | AkbTableQueryEnvelope",
    "  | AkbTableSqlEnvelope",
    "  | AkbFileEnvelope;",
  ];
}

function expectObject(value: unknown, label: string): JsonObject {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as JsonObject;
  }
  throw new TypeError(`${label} must be an object.`);
}

function expectOptionalObject(value: unknown): JsonObject | null {
  if (value === null || value === undefined) return null;
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as JsonObject)
    : null;
}

function stringProp(object: JsonObject | null, key: string): string | null {
  const value = object?.[key];
  return typeof value === "string" && value.length > 0 ? value : null;
}

function operationIdFrom(path: string, method: string): string {
  const words = path.replace(/^\/api\/v1\//, "").match(/[A-Za-z0-9]+/g) ?? ["api"];
  const pascal = words.map((word) => word[0].toUpperCase() + word.slice(1)).join("");
  return `${method}${pascal}`;
}

function tsLiteral(value: string): string {
  return JSON.stringify(value);
}

function tsKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : tsLiteral(key);
}
