/* Generated by akb core OpenAPI codegen. Do not edit manually. */
/* Source: /openapi.json */

import type { AkbErrorPayload, AkbJsonValue } from "../index.js";
import type { AkbOperation } from "./fetch.js";

export type AkbJsonObject = { [key: string]: AkbJsonValue | undefined };
export type AkbJsonObjectArray = AkbJsonObject[];

export interface AkbTableEnvelope {
  kind: "table";
  uri?: string;
  vault?: string;
  collection?: string | null;
  name?: string;
  sql_name?: string;
  description?: string | null;
  columns?: AkbJsonObjectArray;
  unique_keys?: AkbJsonObjectArray;
  indexes?: AkbJsonObjectArray;
  row_count?: number;
  deleted?: boolean;
  items?: AkbJsonObjectArray;
  total?: number;
  [key: string]: unknown;
}

export interface AkbTableMigrationEnvelope {
  kind: "table_migration";
  vault: string;
  idempotency_key: string;
  checksum: string;
  applied: boolean;
  operations: number;
  results: AkbJsonObjectArray;
  id?: string;
  applied_at?: string;
  [key: string]: unknown;
}

export interface AkbTableSchemaEnvelope {
  kind: "table_schema";
  vault: string;
  name: string;
  columns: AkbJsonObjectArray;
  pg_types: Record<string, string>;
  drift: AkbJsonObject;
  uri?: string;
  collection?: string | null;
  table?: string;
  sql_name?: string;
  unique_keys?: AkbJsonObjectArray;
  indexes?: AkbJsonObjectArray;
  system_columns?: string[];
  [key: string]: unknown;
}

export interface AkbVaultTableSchemaEnvelope {
  kind: "vault_table_schema";
  vault: string;
  tables: AkbTableSchemaEnvelope[];
  total: number;
  [key: string]: unknown;
}

export interface AkbTableQueryEnvelope<Row = AkbJsonObject> {
  kind: "table_query";
  columns: string[];
  items: Row[];
  total: number;
  vault?: string;
  table?: string;
  vaults?: string[];
  [key: string]: unknown;
}

export interface AkbTableSqlEnvelope {
  kind: "table_sql";
  vaults: string[];
  result: string;
  [key: string]: unknown;
}

export type AkbSqlEnvelope = AkbTableQueryEnvelope | AkbTableSqlEnvelope;

export interface AkbFileEnvelope {
  kind: "file";
  uri?: string;
  id?: string;
  vault?: string;
  collection?: string | null;
  name?: string;
  mime_type?: string;
  size_bytes?: number;
  description?: string | null;
  upload_url?: string;
  download_url?: string;
  deleted?: boolean;
  items?: AkbJsonObjectArray;
  total?: number;
  [key: string]: unknown;
}

export interface AkbDocumentEnvelope {
  kind: "document";
  uri?: string;
  vault?: string;
  path?: string;
  title?: string;
  type?: string;
  status?: string;
  summary?: string | null;
  domain?: string | null;
  created_by?: string | null;
  created_by_name?: string | null;
  created_at?: string;
  updated_at?: string;
  current_commit?: string | null;
  content_hash?: string | null;
  hash_algorithm?: string | null;
  tags?: string[];
  content?: string | null;
  is_public?: boolean;
  public_slug?: string | null;
  metadata_is_current?: boolean;
  items?: AkbJsonObjectArray;
  hint?: string | null;
  deleted?: boolean;
  [key: string]: unknown;
}

export interface AkbDocumentWriteEnvelope {
  kind: "document_write";
  uri: string;
  vault: string;
  path: string;
  commit_hash: string;
  chunks_indexed: number;
  entities_found: number;
  current_commit?: string | null;
  previous_commit?: string | null;
  content_hash?: string | null;
  previous_content_hash?: string | null;
  hash_algorithm?: string | null;
  action?: string | null;
  [key: string]: unknown;
}

export interface AkbSearchResult {
  source_type: string;
  uri: string;
  vault: string;
  path: string;
  title: string;
  collection?: string | null;
  doc_type?: string | null;
  summary?: string | null;
  tags: string[];
  score: number;
  matched_section?: string | null;
  [key: string]: unknown;
}

export interface AkbSearchEnvelope {
  kind: "search";
  query: string;
  total: number;
  returned: number;
  total_matches: number;
  results: AkbSearchResult[];
  truncated?: boolean;
  hint?: string | null;
  degraded?: boolean;
  degradation_reason?: string | null;
  [key: string]: unknown;
}

export interface AkbDrillDownSection {
  chunk_index: number;
  section_path?: string | null;
  content?: string | null;
  [key: string]: unknown;
}

export interface AkbDrillDownEnvelope {
  kind: "drill_down";
  uri: string;
  sections: AkbDrillDownSection[];
  [key: string]: unknown;
}

export interface AkbGrepMatch {
  text: string;
  section?: string | null;
  [key: string]: unknown;
}

export interface AkbGrepResult {
  uri: string;
  vault: string;
  path: string;
  title: string;
  matches?: AkbGrepMatch[];
  [key: string]: unknown;
}

export interface AkbGrepEnvelope {
  kind: "grep";
  pattern: string;
  regex: boolean;
  error?: string | null;
  returned_docs?: number | null;
  returned_matches?: number | null;
  total_docs?: number | null;
  total_matches?: number | null;
  truncated?: boolean | null;
  hint?: string | null;
  results?: AkbGrepResult[] | null;
  by_doc?: Record<string, number> | null;
  n_files?: number | null;
  files?: string[] | null;
  [key: string]: unknown;
}

export interface AkbCollectionSummary {
  path: string;
  name: string;
  summary: string | null;
  doc_count: number;
}

export interface AkbCollectionCreateEnvelope {
  kind: "collection_create";
  ok: true;
  created: boolean;
  collection: AkbCollectionSummary;
}

export interface AkbCollectionDeleteEnvelope {
  kind: "collection_delete";
  ok: true;
  collection: string;
  deleted_docs: number;
  deleted_files: number;
  deleted_sub_collections: number;
  deleted_tables: number;
}

export interface AkbGraphNode {
  uri: string;
  name: string;
  resource_type: "doc" | "table" | "file";
  depth?: number | null;
  degree?: number | null;
  [key: string]: unknown;
}

export interface AkbGraphEdge {
  source: string;
  target: string;
  relation: AkbRelationType;
  kind: "implicit" | "explicit";
  [key: string]: unknown;
}

export interface AkbGraphNeighborsEnvelope {
  kind: "graph_neighbors";
  nodes: AkbGraphNode[];
  edges: AkbGraphEdge[];
  [key: string]: unknown;
}

export interface AkbGraphOverviewEnvelope {
  kind: "graph_overview";
  nodes: AkbGraphNode[];
  edges: AkbGraphEdge[];
  nodes_total: number;
  edges_total: number;
  returned: number;
  truncated: boolean;
  orphans_returned: number;
  orphans_truncated: boolean;
  [key: string]: unknown;
}

export interface AkbGraphHealthEnvelope {
  kind: "graph_health";
  hubs: AkbGraphNode[];
  orphans: {
    count: number;
    sample: AkbGraphNode[];
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export type AkbGraphEnvelope = AkbGraphNeighborsEnvelope | AkbGraphOverviewEnvelope;

export type AkbWritableRelationType =
  | "depends_on"
  | "related_to"
  | "implements"
  | "references"
  | "attached_to"
  | "derived_from";

export type AkbRelationType = AkbWritableRelationType | "links_to";

export interface AkbRelation {
  direction: "incoming" | "outgoing";
  relation: AkbRelationType;
  uri: string;
  resource_type: "doc" | "table" | "file";
  name?: string | null;
  [key: string]: unknown;
}

export interface AkbRelationsEnvelope {
  kind: "relations";
  uri: string;
  relations: AkbRelation[];
  [key: string]: unknown;
}

export interface AkbRelationLinkEnvelope {
  kind: "relation_link";
  linked: boolean;
  source: string;
  target: string;
  relation: AkbWritableRelationType;
  [key: string]: unknown;
}

export interface AkbRelationUnlinkEnvelope {
  kind: "relation_unlink";
  unlinked: number;
  source: string;
  target: string;
  [key: string]: unknown;
}

export interface AkbProvenanceEnvelope {
  kind: "provenance";
  doc_id: string;
  title: string;
  path: string;
  vault: string;
  uri: string;
  created_by: string | null;
  created_at: string | null;
  updated_at: string | null;
  current_commit: string | null;
  relations: AkbRelation[];
  [key: string]: unknown;
}

export type AkbSuccessEnvelope =
  | AkbTableEnvelope
  | AkbTableMigrationEnvelope
  | AkbTableSchemaEnvelope
  | AkbVaultTableSchemaEnvelope
  | AkbTableQueryEnvelope
  | AkbTableSqlEnvelope
  | AkbFileEnvelope
  | AkbDocumentEnvelope
  | AkbDocumentWriteEnvelope
  | AkbSearchEnvelope
  | AkbDrillDownEnvelope
  | AkbGrepEnvelope
  | AkbCollectionCreateEnvelope
  | AkbCollectionDeleteEnvelope
  | AkbGraphNeighborsEnvelope
  | AkbGraphOverviewEnvelope
  | AkbGraphHealthEnvelope
  | AkbRelationsEnvelope
  | AkbRelationLinkEnvelope
  | AkbRelationUnlinkEnvelope
  | AkbProvenanceEnvelope;

export interface paths {
  "/api/v1/browse/{vault}": {
    get: AkbOperation<"get", "/api/v1/browse/{vault}", { path: { vault: string } }, never, AkbDocumentEnvelope>;
  };
  "/api/v1/collections/{vault}": {
    post: AkbOperation<"post", "/api/v1/collections/{vault}", { path: { vault: string } }, unknown, AkbCollectionCreateEnvelope>;
  };
  "/api/v1/collections/{vault}/{path}": {
    delete: AkbOperation<"delete", "/api/v1/collections/{vault}/{path}", { path: { vault: string; path: string } }, never, AkbCollectionDeleteEnvelope>;
  };
  "/api/v1/documents": {
    post: AkbOperation<"post", "/api/v1/documents", never, unknown, AkbDocumentWriteEnvelope>;
  };
  "/api/v1/documents/{vault}/{doc_id}": {
    delete: AkbOperation<"delete", "/api/v1/documents/{vault}/{doc_id}", { path: { vault: string; doc_id: string } }, never, AkbDocumentEnvelope>;
    get: AkbOperation<"get", "/api/v1/documents/{vault}/{doc_id}", { path: { vault: string; doc_id: string } }, never, AkbDocumentEnvelope>;
    patch: AkbOperation<"patch", "/api/v1/documents/{vault}/{doc_id}", { path: { vault: string; doc_id: string } }, unknown, AkbDocumentWriteEnvelope>;
  };
  "/api/v1/drill-down": {
    get: AkbOperation<"get", "/api/v1/drill-down", never, never, AkbDrillDownEnvelope>;
  };
  "/api/v1/files/{vault}": {
    get: AkbOperation<"get", "/api/v1/files/{vault}", { path: { vault: string } }, never, AkbFileEnvelope>;
  };
  "/api/v1/files/{vault}/upload": {
    post: AkbOperation<"post", "/api/v1/files/{vault}/upload", { path: { vault: string } }, unknown, AkbFileEnvelope>;
  };
  "/api/v1/files/{vault}/{file_id}": {
    delete: AkbOperation<"delete", "/api/v1/files/{vault}/{file_id}", { path: { vault: string; file_id: string } }, never, AkbFileEnvelope>;
  };
  "/api/v1/files/{vault}/{file_id}/confirm": {
    post: AkbOperation<"post", "/api/v1/files/{vault}/{file_id}/confirm", { path: { vault: string; file_id: string } }, unknown, AkbFileEnvelope>;
  };
  "/api/v1/files/{vault}/{file_id}/download": {
    get: AkbOperation<"get", "/api/v1/files/{vault}/{file_id}/download", { path: { vault: string; file_id: string } }, never, AkbFileEnvelope>;
  };
  "/api/v1/graph": {
    get: AkbOperation<"get", "/api/v1/graph", never, never, AkbGraphEnvelope>;
  };
  "/api/v1/graph/health": {
    get: AkbOperation<"get", "/api/v1/graph/health", never, never, AkbGraphHealthEnvelope>;
  };
  "/api/v1/graph/overview": {
    get: AkbOperation<"get", "/api/v1/graph/overview", never, never, AkbGraphOverviewEnvelope>;
  };
  "/api/v1/grep": {
    get: AkbOperation<"get", "/api/v1/grep", never, never, AkbGrepEnvelope>;
  };
  "/api/v1/provenance": {
    get: AkbOperation<"get", "/api/v1/provenance", never, never, AkbProvenanceEnvelope>;
  };
  "/api/v1/relations": {
    delete: AkbOperation<"delete", "/api/v1/relations", never, never, AkbRelationUnlinkEnvelope>;
    get: AkbOperation<"get", "/api/v1/relations", never, never, AkbRelationsEnvelope>;
    post: AkbOperation<"post", "/api/v1/relations", never, unknown, AkbRelationLinkEnvelope>;
  };
  "/api/v1/search": {
    get: AkbOperation<"get", "/api/v1/search", never, never, AkbSearchEnvelope>;
  };
  "/api/v1/tables/{vault}": {
    get: AkbOperation<"get", "/api/v1/tables/{vault}", { path: { vault: string } }, never, AkbTableEnvelope>;
    post: AkbOperation<"post", "/api/v1/tables/{vault}", { path: { vault: string } }, unknown, AkbTableEnvelope>;
  };
  "/api/v1/tables/{vault}/migrations": {
    post: AkbOperation<"post", "/api/v1/tables/{vault}/migrations", { path: { vault: string } }, unknown, AkbTableMigrationEnvelope>;
  };
  "/api/v1/tables/{vault}/schema": {
    get: AkbOperation<"get", "/api/v1/tables/{vault}/schema", { path: { vault: string } }, never, AkbVaultTableSchemaEnvelope>;
  };
  "/api/v1/tables/{vault}/sql": {
    post: AkbOperation<"post", "/api/v1/tables/{vault}/sql", { path: { vault: string } }, unknown, AkbSqlEnvelope>;
  };
  "/api/v1/tables/{vault}/{table_name}": {
    delete: AkbOperation<"delete", "/api/v1/tables/{vault}/{table_name}", { path: { vault: string; table_name: string } }, never, AkbTableEnvelope>;
    patch: AkbOperation<"patch", "/api/v1/tables/{vault}/{table_name}", { path: { vault: string; table_name: string } }, unknown, AkbTableEnvelope>;
  };
  "/api/v1/tables/{vault}/{table}/query": {
    post: AkbOperation<"post", "/api/v1/tables/{vault}/{table}/query", { path: { vault: string; table: string } }, unknown, AkbTableQueryEnvelope | null>;
  };
  "/api/v1/tables/{vault}/{table}/rows": {
    delete: AkbOperation<"delete", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, never, AkbTableQueryEnvelope | null>;
    get: AkbOperation<"get", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, never, AkbTableQueryEnvelope>;
    patch: AkbOperation<"patch", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, unknown, AkbTableQueryEnvelope | null>;
    post: AkbOperation<"post", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, unknown, AkbTableQueryEnvelope | null>;
  };
  "/api/v1/tables/{vault}/{table}/schema": {
    get: AkbOperation<"get", "/api/v1/tables/{vault}/{table}/schema", { path: { vault: string; table: string } }, never, AkbTableSchemaEnvelope>;
  };
}

export interface operations {
  documentsBrowseVault: paths["/api/v1/browse/{vault}"]["get"];
  collectionsCreateCollection: paths["/api/v1/collections/{vault}"]["post"];
  collectionsDeleteCollection: paths["/api/v1/collections/{vault}/{path}"]["delete"];
  documentsPutDocument: paths["/api/v1/documents"]["post"];
  documentsDeleteDocument: paths["/api/v1/documents/{vault}/{doc_id}"]["delete"];
  documentsGetDocument: paths["/api/v1/documents/{vault}/{doc_id}"]["get"];
  documentsUpdateDocument: paths["/api/v1/documents/{vault}/{doc_id}"]["patch"];
  searchDrillDown: paths["/api/v1/drill-down"]["get"];
  filesGetVault: paths["/api/v1/files/{vault}"]["get"];
  filesPostUpload: paths["/api/v1/files/{vault}/upload"]["post"];
  filesDeleteFileId: paths["/api/v1/files/{vault}/{file_id}"]["delete"];
  filesPostFileIdConfirm: paths["/api/v1/files/{vault}/{file_id}/confirm"]["post"];
  filesGetFileIdDownload: paths["/api/v1/files/{vault}/{file_id}/download"]["get"];
  graphNeighbors: paths["/api/v1/graph"]["get"];
  graphHealth: paths["/api/v1/graph/health"]["get"];
  graphOverview: paths["/api/v1/graph/overview"]["get"];
  searchGrepDocuments: paths["/api/v1/grep"]["get"];
  graphProvenance: paths["/api/v1/provenance"]["get"];
  graphUnlink: paths["/api/v1/relations"]["delete"];
  graphRelations: paths["/api/v1/relations"]["get"];
  graphLink: paths["/api/v1/relations"]["post"];
  searchSearchDocuments: paths["/api/v1/search"]["get"];
  tablesGetVault: paths["/api/v1/tables/{vault}"]["get"];
  tablesPostVault: paths["/api/v1/tables/{vault}"]["post"];
  tablesApplyMigration: paths["/api/v1/tables/{vault}/migrations"]["post"];
  tablesGetVaultSchema: paths["/api/v1/tables/{vault}/schema"]["get"];
  tablesPostSql: paths["/api/v1/tables/{vault}/sql"]["post"];
  tablesDeleteTableName: paths["/api/v1/tables/{vault}/{table_name}"]["delete"];
  tablesAlterTable: paths["/api/v1/tables/{vault}/{table_name}"]["patch"];
  tablesQueryRows: paths["/api/v1/tables/{vault}/{table}/query"]["post"];
  tablesDeleteRows: paths["/api/v1/tables/{vault}/{table}/rows"]["delete"];
  tablesSelectRows: paths["/api/v1/tables/{vault}/{table}/rows"]["get"];
  tablesUpdateRows: paths["/api/v1/tables/{vault}/{table}/rows"]["patch"];
  tablesInsertRows: paths["/api/v1/tables/{vault}/{table}/rows"]["post"];
  tablesGetTableSchema: paths["/api/v1/tables/{vault}/{table}/schema"]["get"];
}

export interface components {
  schemas: {
    AkbError: AkbErrorPayload;
    AkbTableEnvelope: AkbTableEnvelope;
    AkbTableMigrationEnvelope: AkbTableMigrationEnvelope;
    AkbTableSchemaEnvelope: AkbTableSchemaEnvelope;
    AkbVaultTableSchemaEnvelope: AkbVaultTableSchemaEnvelope;
    AkbTableQueryEnvelope: AkbTableQueryEnvelope;
    AkbTableSqlEnvelope: AkbTableSqlEnvelope;
    AkbSqlEnvelope: AkbSqlEnvelope;
    AkbFileEnvelope: AkbFileEnvelope;
    AkbDocumentEnvelope: AkbDocumentEnvelope;
    AkbDocumentWriteEnvelope: AkbDocumentWriteEnvelope;
    AkbCollectionSummary: AkbCollectionSummary;
    AkbCollectionCreateEnvelope: AkbCollectionCreateEnvelope;
    AkbCollectionDeleteEnvelope: AkbCollectionDeleteEnvelope;
    AkbSearchEnvelope: AkbSearchEnvelope;
    AkbDrillDownEnvelope: AkbDrillDownEnvelope;
    AkbGrepEnvelope: AkbGrepEnvelope;
    AkbGraphNode: AkbGraphNode;
    AkbGraphEdge: AkbGraphEdge;
    AkbGraphEnvelope: AkbGraphEnvelope;
    AkbGraphNeighborsEnvelope: AkbGraphNeighborsEnvelope;
    AkbGraphOverviewEnvelope: AkbGraphOverviewEnvelope;
    AkbGraphHealthEnvelope: AkbGraphHealthEnvelope;
    AkbRelation: AkbRelation;
    AkbRelationsEnvelope: AkbRelationsEnvelope;
    AkbRelationLinkEnvelope: AkbRelationLinkEnvelope;
    AkbRelationUnlinkEnvelope: AkbRelationUnlinkEnvelope;
    AkbProvenanceEnvelope: AkbProvenanceEnvelope;
  };
}
