/* Generated by akb core OpenAPI codegen. Do not edit manually. */
/* Source: /openapi.json */

import type { AkbErrorPayload, AkbJsonValue } from "../index.js";
import type { AkbOperation } from "./fetch.js";

export type AkbJsonObject = { [key: string]: AkbJsonValue | undefined };
export type AkbJsonObjectArray = AkbJsonObject[];

export interface AkbTableEnvelope {
  kind: "table";
  uri?: string;
  vault?: string;
  collection?: string | null;
  name?: string;
  sql_name?: string;
  description?: string | null;
  columns?: AkbJsonObjectArray;
  unique_keys?: AkbJsonObjectArray;
  indexes?: AkbJsonObjectArray;
  row_count?: number;
  deleted?: boolean;
  items?: AkbJsonObjectArray;
  total?: number;
  [key: string]: unknown;
}

export interface AkbTableMigrationEnvelope {
  kind: "table_migration";
  vault: string;
  idempotency_key: string;
  checksum: string;
  applied: boolean;
  operations: number;
  results: AkbJsonObjectArray;
  id?: string;
  applied_at?: string;
  [key: string]: unknown;
}

export interface AkbTableSchemaEnvelope {
  kind: "table_schema";
  vault: string;
  name: string;
  columns: AkbJsonObjectArray;
  pg_types: Record<string, string>;
  drift: AkbJsonObject;
  uri?: string;
  collection?: string | null;
  table?: string;
  sql_name?: string;
  unique_keys?: AkbJsonObjectArray;
  indexes?: AkbJsonObjectArray;
  system_columns?: string[];
  [key: string]: unknown;
}

export interface AkbVaultTableSchemaEnvelope {
  kind: "vault_table_schema";
  vault: string;
  tables: AkbTableSchemaEnvelope[];
  total: number;
  [key: string]: unknown;
}

export interface AkbTableQueryEnvelope<Row = AkbJsonObject> {
  kind: "table_query";
  columns: string[];
  items: Row[];
  total: number;
  vault?: string;
  table?: string;
  vaults?: string[];
  [key: string]: unknown;
}

export interface AkbTableSqlEnvelope {
  kind: "table_sql";
  vaults: string[];
  result: string;
  [key: string]: unknown;
}

export type AkbSqlEnvelope = AkbTableQueryEnvelope | AkbTableSqlEnvelope;

export interface AkbFileEnvelope {
  kind: "file";
  uri?: string;
  id?: string;
  vault?: string;
  collection?: string | null;
  name?: string;
  mime_type?: string;
  size_bytes?: number;
  description?: string | null;
  upload_url?: string;
  download_url?: string;
  deleted?: boolean;
  items?: AkbJsonObjectArray;
  total?: number;
  [key: string]: unknown;
}

export type AkbSuccessEnvelope =
  | AkbTableEnvelope
  | AkbTableMigrationEnvelope
  | AkbTableSchemaEnvelope
  | AkbVaultTableSchemaEnvelope
  | AkbTableQueryEnvelope
  | AkbTableSqlEnvelope
  | AkbFileEnvelope;

export interface paths {
  "/api/v1/files/{vault}": {
    get: AkbOperation<"get", "/api/v1/files/{vault}", { path: { vault: string } }, never, AkbFileEnvelope>;
  };
  "/api/v1/files/{vault}/upload": {
    post: AkbOperation<"post", "/api/v1/files/{vault}/upload", { path: { vault: string } }, unknown, AkbFileEnvelope>;
  };
  "/api/v1/tables/{vault}": {
    get: AkbOperation<"get", "/api/v1/tables/{vault}", { path: { vault: string } }, never, AkbTableEnvelope>;
    post: AkbOperation<"post", "/api/v1/tables/{vault}", { path: { vault: string } }, unknown, AkbTableEnvelope>;
  };
  "/api/v1/tables/{vault}/migrations": {
    post: AkbOperation<"post", "/api/v1/tables/{vault}/migrations", { path: { vault: string } }, unknown, AkbTableMigrationEnvelope>;
  };
  "/api/v1/tables/{vault}/schema": {
    get: AkbOperation<"get", "/api/v1/tables/{vault}/schema", { path: { vault: string } }, never, AkbVaultTableSchemaEnvelope>;
  };
  "/api/v1/tables/{vault}/sql": {
    post: AkbOperation<"post", "/api/v1/tables/{vault}/sql", { path: { vault: string } }, unknown, AkbSqlEnvelope>;
  };
  "/api/v1/tables/{vault}/{table_name}": {
    delete: AkbOperation<"delete", "/api/v1/tables/{vault}/{table_name}", { path: { vault: string; table_name: string } }, never, AkbTableEnvelope>;
    patch: AkbOperation<"patch", "/api/v1/tables/{vault}/{table_name}", { path: { vault: string; table_name: string } }, unknown, AkbTableEnvelope>;
  };
  "/api/v1/tables/{vault}/{table}/query": {
    post: AkbOperation<"post", "/api/v1/tables/{vault}/{table}/query", { path: { vault: string; table: string } }, unknown, AkbTableQueryEnvelope | null>;
  };
  "/api/v1/tables/{vault}/{table}/rows": {
    delete: AkbOperation<"delete", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, never, AkbTableQueryEnvelope | null>;
    get: AkbOperation<"get", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, never, AkbTableQueryEnvelope>;
    patch: AkbOperation<"patch", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, unknown, AkbTableQueryEnvelope | null>;
    post: AkbOperation<"post", "/api/v1/tables/{vault}/{table}/rows", { path: { vault: string; table: string } }, unknown, AkbTableQueryEnvelope | null>;
  };
  "/api/v1/tables/{vault}/{table}/schema": {
    get: AkbOperation<"get", "/api/v1/tables/{vault}/{table}/schema", { path: { vault: string; table: string } }, never, AkbTableSchemaEnvelope>;
  };
}

export interface operations {
  filesGetVault: paths["/api/v1/files/{vault}"]["get"];
  filesPostUpload: paths["/api/v1/files/{vault}/upload"]["post"];
  tablesGetVault: paths["/api/v1/tables/{vault}"]["get"];
  tablesPostVault: paths["/api/v1/tables/{vault}"]["post"];
  tablesApplyMigration: paths["/api/v1/tables/{vault}/migrations"]["post"];
  tablesGetVaultSchema: paths["/api/v1/tables/{vault}/schema"]["get"];
  tablesPostSql: paths["/api/v1/tables/{vault}/sql"]["post"];
  tablesDeleteTableName: paths["/api/v1/tables/{vault}/{table_name}"]["delete"];
  tablesAlterTable: paths["/api/v1/tables/{vault}/{table_name}"]["patch"];
  tablesQueryRows: paths["/api/v1/tables/{vault}/{table}/query"]["post"];
  tablesDeleteRows: paths["/api/v1/tables/{vault}/{table}/rows"]["delete"];
  tablesSelectRows: paths["/api/v1/tables/{vault}/{table}/rows"]["get"];
  tablesUpdateRows: paths["/api/v1/tables/{vault}/{table}/rows"]["patch"];
  tablesInsertRows: paths["/api/v1/tables/{vault}/{table}/rows"]["post"];
  tablesGetTableSchema: paths["/api/v1/tables/{vault}/{table}/schema"]["get"];
}

export interface components {
  schemas: {
    AkbError: AkbErrorPayload;
    AkbTableEnvelope: AkbTableEnvelope;
    AkbTableMigrationEnvelope: AkbTableMigrationEnvelope;
    AkbTableSchemaEnvelope: AkbTableSchemaEnvelope;
    AkbVaultTableSchemaEnvelope: AkbVaultTableSchemaEnvelope;
    AkbTableQueryEnvelope: AkbTableQueryEnvelope;
    AkbTableSqlEnvelope: AkbTableSqlEnvelope;
    AkbSqlEnvelope: AkbSqlEnvelope;
    AkbFileEnvelope: AkbFileEnvelope;
  };
}
