/**
 * Generate Supabase-style AKB table types from the runtime schema
 * introspection JSON returned by `GET /tables/{vault}/schema`.
 */

/** @typedef {Record<string, unknown>} JsonObject */

const TYPE_MAP = new Map([
  ["text", "string"],
  ["int", "number"],
  ["float", "number"],
  ["numeric", "number"],
  ["number", "number"],
  ["boolean", "boolean"],
  ["uuid", "string"],
  ["date", "string"],
  ["timestamp", "string"],
  ["jsonb", "Json"],
  ["json", "Json"],
  ["text[]", "string[]"],
]);

/**
 * @param {unknown} schema
 * @returns {string}
 */
export function generateAkbSchema(schema) {
  const normalized = normalizeSchema(schema);
  const lines = [
    "/* Generated by akb gen types. Do not edit manually. */",
    `/* Source vault: ${normalized.vault} */`,
    "",
    "export type Json =",
    "  | string",
    "  | number",
    "  | boolean",
    "  | null",
    "  | { [key: string]: Json | undefined }",
    "  | Json[];",
    "",
    "export type AkbRef<T, Target extends string> = T & { readonly __akbRef?: Target };",
    "",
    "export interface Database {",
    "  public: {",
    "    Tables: {",
  ];

  for (const table of normalized.tables) {
    lines.push(...renderTable(table));
  }

  lines.push(
    "    };",
    "  };",
    "}",
    "",
    "export type AkbSchema = Database;",
    "",
  );
  return lines.join("\n");
}

/**
 * @param {unknown} schema
 * @returns {{ vault: string, tables: JsonObject[] }}
 */
function normalizeSchema(schema) {
  const root = expectObject(schema, "schema");
  const kind = stringProp(root, "kind");
  if (kind === "table_schema") {
    return {
      vault: stringProp(root, "vault") ?? "default",
      tables: [root],
    };
  }
  if (kind !== "vault_table_schema") {
    throw new TypeError("Expected a table_schema or vault_table_schema response.");
  }
  const rawTables = root.tables;
  if (!Array.isArray(rawTables)) {
    throw new TypeError("vault_table_schema.tables must be an array.");
  }
  return {
    vault: stringProp(root, "vault") ?? "default",
    tables: rawTables.map((item, index) => expectObject(item, `tables[${index}]`))
      .sort((a, b) => tableName(a).localeCompare(tableName(b))),
  };
}

/**
 * @param {JsonObject} table
 * @returns {string[]}
 */
function renderTable(table) {
  const name = tableName(table);
  const columns = columnList(table);
  const lines = [
    `      ${tsKey(name)}: {`,
    "        Row: {",
  ];
  for (const column of columns) {
    lines.push(`          ${tsKey(columnName(column))}: ${rowType(column)};`);
  }
  lines.push("        };", "        Insert: {");
  for (const column of columns) {
    const key = tsKey(columnName(column));
    const optional = insertRequired(column) ? "" : "?";
    lines.push(`          ${key}${optional}: ${insertType(column)};`);
  }
  lines.push("        };", "        Update: {");
  for (const column of columns) {
    lines.push(`          ${tsKey(columnName(column))}?: ${rowType(column)};`);
  }
  lines.push("        };", "        Relationships: [");
  const relationships = columns.flatMap((column) => renderRelationship(name, column));
  lines.push(...relationships);
  lines.push("        ];", "      };");
  return lines;
}

/**
 * @param {JsonObject} table
 * @returns {JsonObject[]}
 */
function columnList(table) {
  if (!Array.isArray(table.columns)) {
    throw new TypeError(`Table ${tableName(table)} is missing a columns array.`);
  }
  return table.columns.map((item, index) => expectObject(item, `${tableName(table)}.columns[${index}]`));
}

/**
 * @param {JsonObject} column
 * @returns {string}
 */
function rowType(column) {
  const type = scalarType(column);
  return column.required === true ? type : `${type} | null`;
}

/**
 * @param {JsonObject} column
 * @returns {string}
 */
function insertType(column) {
  if (column.required === true) {
    return scalarType(column);
  }
  return rowType(column);
}

/**
 * @param {JsonObject} column
 * @returns {boolean}
 */
function insertRequired(column) {
  return column.required === true && !hasDefault(column);
}

/**
 * @param {JsonObject} column
 * @returns {boolean}
 */
function hasDefault(column) {
  return column.default !== null && column.default !== undefined;
}

/**
 * @param {JsonObject} column
 * @returns {string}
 */
function scalarType(column) {
  const enumType = enumUnion(column.enum);
  const baseType = enumType ?? TYPE_MAP.get(stringProp(column, "type") ?? "text") ?? "unknown";
  const reference = referenceTarget(column);
  if (!reference) return baseType;
  return `AkbRef<${baseType}, ${tsLiteral(reference)}>`;
}

/**
 * @param {unknown} values
 * @returns {string | null}
 */
function enumUnion(values) {
  if (!Array.isArray(values) || values.length === 0) return null;
  const literals = values.map((value) => {
    if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
      return tsLiteral(value);
    }
    return null;
  });
  if (literals.some((value) => value === null)) return null;
  return /** @type {string[]} */ (literals).join(" | ");
}

/**
 * @param {string} tableNameValue
 * @param {JsonObject} column
 * @returns {string[]}
 */
function renderRelationship(tableNameValue, column) {
  const reference = expectOptionalObject(column.references);
  if (!reference) return [];
  const table = stringProp(reference, "table") ?? stringProp(reference, "referenced_table");
  const referencedColumn = stringProp(reference, "column") ?? stringProp(reference, "referenced_column");
  if (!table || !referencedColumn) return [];
  const columnValue = columnName(column);
  const onDelete = stringProp(column, "on_delete");
  return [
    "          {",
    `            foreignKeyName: ${tsLiteral(`${tableNameValue}_${columnValue}_fkey`)};`,
    `            columns: [${tsLiteral(columnValue)}];`,
    "            isOneToOne: false;",
    `            referencedRelation: ${tsLiteral(table)};`,
    `            referencedColumns: [${tsLiteral(referencedColumn)}];`,
    ...(onDelete ? [`            onDelete: ${tsLiteral(onDelete)};`] : []),
    "          },",
  ];
}

/**
 * @param {JsonObject} column
 * @returns {string | null}
 */
function referenceTarget(column) {
  const reference = expectOptionalObject(column.references);
  if (!reference) return null;
  const table = stringProp(reference, "table") ?? stringProp(reference, "referenced_table");
  const referencedColumn = stringProp(reference, "column") ?? stringProp(reference, "referenced_column");
  return table && referencedColumn ? `${table}.${referencedColumn}` : null;
}

/**
 * @param {JsonObject} table
 * @returns {string}
 */
function tableName(table) {
  const name = stringProp(table, "name") ?? stringProp(table, "table");
  if (!name) throw new TypeError("Table schema is missing a name.");
  return name;
}

/**
 * @param {JsonObject} column
 * @returns {string}
 */
function columnName(column) {
  const name = stringProp(column, "name");
  if (!name) throw new TypeError("Column schema is missing a name.");
  return name;
}

/**
 * @param {JsonObject} object
 * @param {string} key
 * @returns {string | null}
 */
function stringProp(object, key) {
  const value = object[key];
  return typeof value === "string" && value.length > 0 ? value : null;
}

/**
 * @param {unknown} value
 * @param {string} label
 * @returns {JsonObject}
 */
function expectObject(value, label) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object.`);
  }
  return /** @type {JsonObject} */ (value);
}

/**
 * @param {unknown} value
 * @returns {JsonObject | null}
 */
function expectOptionalObject(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  return /** @type {JsonObject} */ (value);
}

/**
 * @param {string} value
 * @returns {string}
 */
function tsKey(value) {
  return JSON.stringify(value);
}

/**
 * @param {string | number | boolean} value
 * @returns {string}
 */
function tsLiteral(value) {
  return JSON.stringify(value);
}
