/**
 * Generate Supabase-style AKB table types from the runtime schema
 * introspection JSON returned by `GET /tables/{vault}/schema`.
 */

type JsonObject = Record<string, unknown>;

const TYPE_MAP = new Map<string, string>([
  ["text", "string"],
  ["int", "number"],
  ["float", "number"],
  ["numeric", "number"],
  ["number", "number"],
  ["boolean", "boolean"],
  ["uuid", "string"],
  ["date", "string"],
  ["timestamp", "string"],
  ["jsonb", "Json"],
  ["json", "Json"],
  ["text[]", "string[]"],
  ["enum", "string"],
]);

export function generateAkbSchema(schema: unknown): string {
  const normalized = normalizeSchema(schema);
  const lines = [
    "/* Generated by akb gen types. Do not edit manually. */",
    `/* Source vault: ${normalized.vault} */`,
    "",
    "export type Json =",
    "  | string",
    "  | number",
    "  | boolean",
    "  | null",
    "  | { [key: string]: Json | undefined }",
    "  | Json[];",
    "",
    "export type AkbRef<T, Target extends string> = T & { readonly __akbRef?: Target };",
    "",
    "export interface Database {",
    "  public: {",
    "    Tables: {",
  ];

  for (const table of normalized.tables) {
    lines.push(...renderTable(table));
  }

  lines.push(
    "    };",
    "  };",
    "}",
    "",
    "export type AkbSchema = Database;",
    "",
  );
  return lines.join("\n");
}

function normalizeSchema(schema: unknown): { vault: string; tables: JsonObject[] } {
  const root = expectObject(schema, "schema");
  const kind = stringProp(root, "kind");
  if (kind === "table_schema") {
    return {
      vault: stringProp(root, "vault") ?? "default",
      tables: [root],
    };
  }
  if (kind !== "vault_table_schema") {
    throw new TypeError("Expected a table_schema or vault_table_schema response.");
  }
  const rawTables = root.tables;
  if (!Array.isArray(rawTables)) {
    throw new TypeError("vault_table_schema.tables must be an array.");
  }
  return {
    vault: stringProp(root, "vault") ?? "default",
    tables: rawTables.map((item, index) => expectObject(item, `tables[${index}]`))
      .sort((a, b) => tableName(a).localeCompare(tableName(b))),
  };
}

function renderTable(table: JsonObject): string[] {
  const name = tableName(table);
  const columns = columnList(table);
  const lines = [
    `      ${tsKey(name)}: {`,
    "        Row: {",
  ];
  for (const column of columns) {
    lines.push(`          ${tsKey(columnName(column))}: ${rowType(column)};`);
  }
  lines.push("        };", "        Insert: {");
  for (const column of columns) {
    const key = tsKey(columnName(column));
    const optional = insertRequired(column) ? "" : "?";
    lines.push(`          ${key}${optional}: ${insertType(column)};`);
  }
  lines.push("        };", "        Update: {");
  for (const column of columns) {
    lines.push(`          ${tsKey(columnName(column))}?: ${rowType(column)};`);
  }
  lines.push("        };", "        Relationships: [");
  const relationships = columns.flatMap((column) => renderRelationship(name, column));
  lines.push(...relationships);
  lines.push("        ];", "      };");
  return lines;
}

function columnList(table: JsonObject): JsonObject[] {
  if (!Array.isArray(table.columns)) {
    throw new TypeError(`Table ${tableName(table)} is missing a columns array.`);
  }
  return table.columns.map((item, index) => expectObject(item, `${tableName(table)}.columns[${index}]`));
}

function rowType(column: JsonObject): string {
  const type = scalarType(column);
  return column.required === true ? type : `${type} | null`;
}

function insertType(column: JsonObject): string {
  if (column.required === true) {
    return scalarType(column);
  }
  return rowType(column);
}

function insertRequired(column: JsonObject): boolean {
  return column.required === true && !hasDefault(column);
}

function hasDefault(column: JsonObject): boolean {
  return column.default !== null && column.default !== undefined;
}

function scalarType(column: JsonObject): string {
  const enumType = enumUnion(column.enum);
  const baseType = enumType ?? TYPE_MAP.get(stringProp(column, "type") ?? "text") ?? "unknown";
  const reference = referenceTarget(column);
  if (!reference) return baseType;
  return `AkbRef<${baseType}, ${tsLiteral(reference)}>`;
}

function enumUnion(values: unknown): string | null {
  if (!Array.isArray(values) || values.length === 0) return null;
  const literals = values.map((value) => {
    if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
      return tsLiteral(value);
    }
    return null;
  });
  if (literals.some((value) => value === null)) return null;
  return (literals as string[]).join(" | ");
}

function renderRelationship(tableNameValue: string, column: JsonObject): string[] {
  const reference = expectOptionalObject(column.references);
  if (!reference) return [];
  const table = stringProp(reference, "table") ?? stringProp(reference, "referenced_table");
  const referencedColumn = stringProp(reference, "column") ?? stringProp(reference, "referenced_column");
  if (!table || !referencedColumn) return [];
  const columnValue = columnName(column);
  const onDelete = stringProp(column, "on_delete");
  return [
    "          {",
    `            foreignKeyName: ${tsLiteral(`${tableNameValue}_${columnValue}_fkey`)};`,
    `            columns: [${tsLiteral(columnValue)}];`,
    "            isOneToOne: false;",
    `            referencedRelation: ${tsLiteral(table)};`,
    `            referencedColumns: [${tsLiteral(referencedColumn)}];`,
    ...(onDelete ? [`            onDelete: ${tsLiteral(onDelete)};`] : []),
    "          },",
  ];
}

function referenceTarget(column: JsonObject): string | null {
  const reference = expectOptionalObject(column.references);
  if (!reference) return null;
  const table = stringProp(reference, "table") ?? stringProp(reference, "referenced_table");
  const referencedColumn = stringProp(reference, "column") ?? stringProp(reference, "referenced_column");
  return table && referencedColumn ? `${table}.${referencedColumn}` : null;
}

function tableName(table: JsonObject): string {
  const name = stringProp(table, "name") ?? stringProp(table, "table");
  if (!name) throw new TypeError("Table schema is missing a name.");
  return name;
}

function columnName(column: JsonObject): string {
  const name = stringProp(column, "name");
  if (!name) throw new TypeError("Column schema is missing a name.");
  return name;
}

function stringProp(object: JsonObject, key: string): string | null {
  const value = object[key];
  return typeof value === "string" && value.length > 0 ? value : null;
}

function expectObject(value: unknown, label: string): JsonObject {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object.`);
  }
  return value as JsonObject;
}

function expectOptionalObject(value: unknown): JsonObject | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  return value as JsonObject;
}

function tsKey(value: string): string {
  return JSON.stringify(value);
}

function tsLiteral(value: string | number | boolean): string {
  return JSON.stringify(value);
}
